#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 15, 2018 10:02:25 PM


import sys
from tkinter import messagebox
from firebase import firebase

import Admin_Home

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def Admin_validation():
    username = w.Admin_username.get()
    password = w.Admin_password.get()
    if(username == ""):
        messagebox.showerror("Admin Login","Please Enter Your Username")
    else:
        if(password==""):
            messagebox.showerror("Admin Login","Please Enter Your Password")
        else:
            fire = firebase.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/", None)
            result = fire.get("merchant","admin")
            if((result["username"] == username) and (result["password"]==password)):
                messagebox.showinfo("Admin Login", "Welcome")
                destroy_window()
                import Employee_Home
                Employee_Home.vp_start_gui()

            else:
                messagebox.showerror("Admin Login","Username Or Password Is Incorrect")

def Admin_Cancel():
    destroy_window()






#if __name__ == '__main__':
    #import Admin
   # Admin.vp_start_gui()


