#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 01:25:05 AM


import sys
from tkinter import messagebox

from firebase.firebase import FirebaseApplication

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def Add_product_Cancel():
    destroy_window()
    import Employee_Home
    Employee_Home.vp_start_gui()


def Add_product_save():
    PNo = w.P_Number.get()
    Pname = w.P_Name.get()
    PPri = w.P_Price.get()
    Pqun = w.P_Quantity.get()
    if PNo == "":
        messagebox.showerror("Product Number","Please Enter Product Number")
    elif Pname == "":
        messagebox.showerror("Product Name ","Please Enter Product Name")
    elif PPri == "":
        messagebox.showerror("Product Price","Please Enter Product Price")
    elif Pqun =="":
        messagebox.showerror("Product Quantity","Please Enter Product Quantity")
    else:
        if (check_pno(PNo)):
            try:
                PChane = float(PPri)
                pqty = int(Pqun)
                fire = FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/product", None)
                fire.put("Product", PNo, {"ProductName": Pname, "ProductPrice": PChane, "ProductQuantity": pqty})
                messagebox.showinfo("Add Product", "Product Saved")
                destroy_window()
            except ValueError:
                messagebox.showerror("Add Product", "Please Enter A Valid Input")

def check_pno(PNo):
    fire = FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/product", None)
    result = fire.get("Product", None)
    if result != None:
         for key in result.keys():
             if key == PNo:
                 messagebox.showerror("Add Product", "Product No Is Available")
                 return False
                 break
         else:
            return True


#if __name__ == '__main__':
 #   import AdminAddProduct
  #  AdminAddProduct.vp_start_gui()


