#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 08:12:17 PM


import sys
from tkinter import messagebox

from firebase import firebase

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def Change_Password():
    print('ChangePassword_support.Change_Password')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
#class OldPassword(RuntimeError):

def Change_Password():
    from StockerLogin_support import idno
    OldP = w.Old_password.get()
    Newp = w.New_password.get()
    Retp = w.retype_password.get()
    if OldP == "":
        messagebox.showerror("password","Please Enter Your Current Password")
    else:
        if Newp =="":
            messagebox.showerror("Password","Please Enter New Password")
        else:
            if Retp =="":
                messagebox.showerror("password","Please Retype Of New Password")
            else:
                fire = firebase.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/employee/stocker", None)
                result = fire.get("stocker",idno)
                paas = result["password"]
                na = result["name"]
                con = result["phone"]
                if OldP == paas:
                    if Newp == Retp:
                        fire = firebase.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/employee/stocker",None)
                        fire.put("stocker",idno,{"name":na,"password":Retp,"phone":con})
                        messagebox.showinfo("Paasword changed","Password Changed Successfully")
                        destroy_window()
                        import Stocker_Home
                        Stocker_Home.vp_start_gui()
                    else:
                        messagebox.showerror("Password Input","Retype Password Not matching")
                else:
                    messagebox.showerror("Password","Please Enter Your Old Password First")






#if __name__ == '__main__':
 #   import ChangePassword
 #   ChangePassword.vp_start_gui()


