#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 31, 2018 01:13:29 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DispatcherRegistration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Dispatcher_Registration (root)
    DispatcherRegistration_support.init(root, top)
    root.mainloop()

w = None
def create_Dispatcher_Registration(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Dispatcher_Registration (w)
    DispatcherRegistration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Dispatcher_Registration():
    global w
    w.destroy()
    w = None


class Dispatcher_Registration:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("682x506+412+131")
        top.title("Dispatcher Registration")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#93d3d8")
        self.Frame1.configure(width=685)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.04, rely=0.04, height=31, width=244)
        self.Label1.configure(background="#93d3d8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Dispatcher Registration''')
        self.Label1.configure(width=244)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.01, rely=0.18, height=31, width=64)
        self.Label2.configure(background="#93d3d8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''IDNO''')
        self.Label2.configure(width=64)

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.01, rely=0.29, height=31, width=74)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#93d3d8")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font9)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Name''')
        self.Label2_1.configure(width=74)

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.01, rely=0.41, height=31, width=74)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#93d3d8")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font9)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Phone''')
        self.Label2_2.configure(width=74)

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.01, rely=0.52, height=31, width=104)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#93d3d8")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font9)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Password''')
        self.Label2_3.configure(width=104)

        self.Dispatcher_username = Entry(self.Frame1)
        self.Dispatcher_username.place(relx=0.16, rely=0.3, height=30
                , relwidth=0.24)
        self.Dispatcher_username.configure(background="white")
        self.Dispatcher_username.configure(disabledforeground="#a3a3a3")
        self.Dispatcher_username.configure(font="TkFixedFont")
        self.Dispatcher_username.configure(foreground="#000000")
        self.Dispatcher_username.configure(insertbackground="black")
        self.Dispatcher_username.configure(width=164)

        self.Dispatcher_phone = Entry(self.Frame1)
        self.Dispatcher_phone.place(relx=0.16, rely=0.41, height=30
                , relwidth=0.24)
        self.Dispatcher_phone.configure(background="white")
        self.Dispatcher_phone.configure(disabledforeground="#a3a3a3")
        self.Dispatcher_phone.configure(font="TkFixedFont")
        self.Dispatcher_phone.configure(foreground="#000000")
        self.Dispatcher_phone.configure(highlightbackground="#d9d9d9")
        self.Dispatcher_phone.configure(highlightcolor="black")
        self.Dispatcher_phone.configure(insertbackground="black")
        self.Dispatcher_phone.configure(selectbackground="#c4c4c4")
        self.Dispatcher_phone.configure(selectforeground="black")

        self.Dispatcher_pass = Entry(self.Frame1)
        self.Dispatcher_pass.place(relx=0.16, rely=0.52, height=30
                , relwidth=0.24)
        self.Dispatcher_pass.configure(background="white")
        self.Dispatcher_pass.configure(disabledforeground="#a3a3a3")
        self.Dispatcher_pass.configure(font="TkFixedFont")
        self.Dispatcher_pass.configure(foreground="#000000")
        self.Dispatcher_pass.configure(highlightbackground="#d9d9d9")
        self.Dispatcher_pass.configure(highlightcolor="black")
        self.Dispatcher_pass.configure(insertbackground="black")
        self.Dispatcher_pass.configure(selectbackground="#c4c4c4")
        self.Dispatcher_pass.configure(selectforeground="black")

        self.Label2_6 = Label(self.Frame1)
        self.Label2_6.place(relx=0.18, rely=0.18, height=31, width=114)
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(background="#93d3d8")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(font=font9)
        self.Label2_6.configure(foreground="#000000")
        self.Label2_6.configure(highlightbackground="#d9d9d9")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(text='''......''')
        self.Label2_6.configure(width=114)
        idno = DispatcherRegistration_support.dautogen_id()
        self.Label2_6.configure(text=idno)

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.21, rely=0.63, height=34, width=87)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#93d3d8")
        self.Button1.configure(borderwidth="1")
        self.Button1.configure(command=DispatcherRegistration_support.dispatcher_save)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')
        self.Button1.configure(width=87)

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.5, rely=0.0, relheight=1.0, relwidth=0.0)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#161616")
        self.Frame2.configure(width=-5)

        self.Label1_7 = Label(self.Frame1)
        self.Label1_7.place(relx=0.56, rely=0.04, height=31, width=244)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#93d3d8")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font=font9)
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''View Dispatcher''')

        self.Label2_8 = Label(self.Frame1)
        self.Label2_8.place(relx=0.52, rely=0.18, height=31, width=64)
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#93d3d8")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font=font9)
        self.Label2_8.configure(foreground="#000000")
        self.Label2_8.configure(highlightbackground="#d9d9d9")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(text='''IDNO''')

        self.View_Id_Entry = Entry(self.Frame1)
        self.View_Id_Entry.place(relx=0.64, rely=0.18,height=30, relwidth=0.24)
        self.View_Id_Entry.configure(background="white")
        self.View_Id_Entry.configure(disabledforeground="#a3a3a3")
        self.View_Id_Entry.configure(font="TkFixedFont")
        self.View_Id_Entry.configure(foreground="#000000")
        self.View_Id_Entry.configure(insertbackground="black")
        self.View_Id_Entry.configure(width=164)

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.51, rely=0.41, height=31, width=74)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#93d3d8")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font9)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Name''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.52, rely=0.52, height=31, width=74)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#93d3d8")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font9)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Phone''')

        self.Button2 = Button(self.Frame1)
        self.Button2.place(relx=0.71, rely=0.28, height=34, width=77)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#93d3d8")
        self.Button2.configure(borderwidth="1")
        self.Button2.configure(command=DispatcherRegistration_support.dispatcher_view)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font9)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''View''')
        self.Button2.configure(width=77)

        self.Label2_4 = Label(self.Frame1)
        self.Label2_4.place(relx=0.71, rely=0.4, height=31, width=114)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#93d3d8")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(font=font9)
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''......''')

        self.Label2_5 = Label(self.Frame1)
        self.Label2_5.place(relx=0.71, rely=0.53, height=31, width=114)
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(activeforeground="black")
        self.Label2_5.configure(background="#93d3d8")
        self.Label2_5.configure(disabledforeground="#a3a3a3")
        self.Label2_5.configure(font=font9)
        self.Label2_5.configure(foreground="#000000")
        self.Label2_5.configure(highlightbackground="#d9d9d9")
        self.Label2_5.configure(highlightcolor="black")
        self.Label2_5.configure(text='''......''')

        self.Button2_6 = Button(self.Frame1)
        self.Button2_6.place(relx=0.72, rely=0.65, height=34, width=77)
        self.Button2_6.configure(activebackground="#d9d9d9")
        self.Button2_6.configure(activeforeground="#000000")
        self.Button2_6.configure(background="#93d3d8")
        self.Button2_6.configure(borderwidth="1")
        self.Button2_6.configure(command=DispatcherRegistration_support.dispatcher_delete)
        self.Button2_6.configure(disabledforeground="#a3a3a3")
        self.Button2_6.configure(font=font9)
        self.Button2_6.configure(foreground="#000000")
        self.Button2_6.configure(highlightbackground="#d9d9d9")
        self.Button2_6.configure(highlightcolor="black")
        self.Button2_6.configure(pady="0")
        self.Button2_6.configure(text='''Delete''')






if __name__ == '__main__':
    vp_start_gui()



