#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 10, 2018 12:06:06 AM


import sys
from tkinter import messagebox
from firebase import firebase
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def Change_Paas():
    print('DispatcherPassword_support.Change_Paas')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
def Change_Paas():
    from DispatcherLogin_support import idno
    OldP = w.Old_Pass.get()
    Newp = w.New_Pass.get()
    Retp = w.Retype_Pass.get()
    if OldP == "":
        messagebox.showerror("password", "Please Enter Your Current Password")
    else:
        if Newp == "":
            messagebox.showerror("Password", "Please Enter New Password")
        else:
            if Retp == "":
                messagebox.showerror("password", "Please Retype Of New Password")
            else:
                fire = firebase.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/merchant/employee/dispatcher", None)
                result = fire.get("dispatcher", idno)
                paas = result["password"]
                na = result["name"]
                con = result["phone"]
                if OldP == paas:
                    if Newp == Retp:
                        fire = firebase.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/merchant/employee/dispatcher", None)
                        fire.put("dispatcher", idno, {"name": na, "password": Retp, "phone": con})
                        messagebox.showinfo("Paasword changed", "Password Changed Successfully")
                        destroy_window()
                        import DispatcherHome
                        DispatcherHome.vp_start_gui()
                    else:
                        messagebox.showerror("Password Input", "Retype Password Not Matching")

                else:
                    messagebox.showerror("Password ","Please Enter Your Old Password First")
#if __name__ == '__main__':
 #   import DispatcherPassword
  #  DispatcherPassword.vp_start_gui()


