#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 10, 2018 02:36:39 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DispatcherPassword_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    DispatcherPassword_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    DispatcherPassword_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("463x450+417+135")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=-0.01, rely=0.01, relheight=0.99, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#b6afd8")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=455)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.18, rely=0.07, height=31, width=254)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#b6afd8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Dipatcher Password''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.02, rely=0.29, height=31, width=164)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#b6afd8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Enter Old Password''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.01, rely=0.45, height=31, width=164)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#b6afd8")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font10)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Enter New Password''')

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.02, rely=0.61, height=31, width=134)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#b6afd8")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font10)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Retype Password''')
        self.Label2_2.configure(width=134)

        self.Old_Pass = Entry(self.Frame1)
        self.Old_Pass.place(relx=0.43, rely=0.29,height=30, relwidth=0.47)
        self.Old_Pass.configure(background="white")
        self.Old_Pass.configure(disabledforeground="#a3a3a3")
        self.Old_Pass.configure(font="TkFixedFont")
        self.Old_Pass.configure(foreground="#000000")
        self.Old_Pass.configure(highlightbackground="#d9d9d9")
        self.Old_Pass.configure(highlightcolor="black")
        self.Old_Pass.configure(insertbackground="black")
        self.Old_Pass.configure(selectbackground="#c4c4c4")
        self.Old_Pass.configure(selectforeground="black")

        self.New_Pass = Entry(self.Frame1)
        self.New_Pass.place(relx=0.43, rely=0.45,height=30, relwidth=0.47)
        self.New_Pass.configure(background="white")
        self.New_Pass.configure(disabledforeground="#a3a3a3")
        self.New_Pass.configure(font="TkFixedFont")
        self.New_Pass.configure(foreground="#000000")
        self.New_Pass.configure(highlightbackground="#d9d9d9")
        self.New_Pass.configure(highlightcolor="black")
        self.New_Pass.configure(insertbackground="black")
        self.New_Pass.configure(selectbackground="#c4c4c4")
        self.New_Pass.configure(selectforeground="black")

        self.Retype_Pass = Entry(self.Frame1)
        self.Retype_Pass.place(relx=0.43, rely=0.61,height=30, relwidth=0.47)
        self.Retype_Pass.configure(background="white")
        self.Retype_Pass.configure(disabledforeground="#a3a3a3")
        self.Retype_Pass.configure(font="TkFixedFont")
        self.Retype_Pass.configure(foreground="#000000")
        self.Retype_Pass.configure(highlightbackground="#d9d9d9")
        self.Retype_Pass.configure(highlightcolor="black")
        self.Retype_Pass.configure(insertbackground="black")
        self.Retype_Pass.configure(selectbackground="#c4c4c4")
        self.Retype_Pass.configure(selectforeground="black")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.55, rely=0.76, height=44, width=107)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#b6afd8")
        self.Button1.configure(borderwidth="7")
        self.Button1.configure(command=DispatcherPassword_support.Change_Paas)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Change''')






if __name__ == '__main__':
    vp_start_gui()



