#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 27, 2018 12:53:05 AM


import sys
from firebase import firebase
from tkinter import messagebox
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
def sautogen_id():
    fire = firebase.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/merchant/employee/stocker", None)
    result = fire.get("stocker", None)
    idno = ""
    if result == None:
        idno = "100"
    else:
        for x in result:
            pass
        id = int(x)
        id = id + 1
        idno = str(id)

    return idno

def view_stocker():
    idno = w.Stocker_idno.get()
    if idno == "":
        messagebox.showerror("View", "Enter Idno")
    else:
        fire = firebase.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/merchant/employee/stocker", None)
        result = fire.get("stocker", idno)
        if result == None:
            messagebox.showerror("View", "Invalid Idno")
            w.Stocker_idno.delete(0, "end")
        else:
            name = result["name"]
            pno = result["phone"]
            w.Label3_7.configure(text=pno)
            w.Label3_6.configure(text=name)


def save_stocker():
    idno = sautogen_id()
    name = w.Stocker_username.get()
    cno = w.Stocker_cno.get()
    password = w.Stocker_Pass.get()

    if name == "":
        messagebox.showerror("Registration", "Enter Name")
    elif cno == "":
        messagebox.showerror("Registration", "Enter Phone No")
    elif password == "":
        messagebox.showerror("Registration", "Enter Password")
    else:
        fire = firebase.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/merchant/employee/stocker", None)
        fire.put("stocker", idno, {"name": name, "phone": cno, "password": password})
        messagebox.showinfo("Registration", "Saved")
        destroy_window()


def delete_stocker():
    idno = w.Stocker_idno.get()
    if idno == "":
        messagebox.showerror("View", "Enter Idno")
    else:
        ans = messagebox.askyesno("Stocker Delete", "ARE YOU SURE")
        if ans:
            fire = firebase.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/merchant/employee/stocker", None)
            fire.delete("stocker",idno)
            messagebox.showinfo("Delete Confirmation", "Record Deleted")
            destroy_window()


#if __name__ == '__main__':
 #   import Stocker_Reg
  #  Stocker_Reg.vp_start_gui()


