#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 27, 2018 03:05:57 PM


import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def stocker_logout():
    if messagebox.askyesno("Logout","Are You Sure"):
        destroy_window()


def stocker_view_product():
    destroy_window()
    import ProductList
    ProductList.vp_start_gui()
    destroy_window()
    import Stocker_Home
    Stocker_Home.vp_start_gui()

def stocker_add_product():
    destroy_window()
    import AddProduct
    AddProduct.vp_start_gui()
    import Stocker_Home
    Stocker_Home.vp_start_gui()

def stocker_change_password():
    destroy_window()
    import ChangePassword
    ChangePassword.vp_start_gui()