#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 26, 2018 11:57:58 PM


import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def admin_stocker():
    destroy_window()
    import Stocker_Reg
    Stocker_Reg.vp_start_gui()
    #destroy_window()
    import Employee_Home
    Employee_Home.vp_start_gui()
def admin_dispatcher():
    destroy_window()
    import DispatcherRegistration
    DispatcherRegistration.vp_start_gui()
    #destroy_window()
    import Employee_Home
    Employee_Home.vp_start_gui()
def admin_product():
    print("product")
def admin_sales():
    print("sales")
def admin_logout():
    ans = messagebox.askyesno("Admin Logout", "Are You Sure")
    if ans:
        destroy_window()


if __name__ == '__main__':
    import Employee_Home
    Employee_Home.vp_start_gui()


