#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 20, 2018 07:55:25 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import admin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = adminlogin (root)
    admin_support.init(root, top)
    root.mainloop()

w = None
def create_adminlogin(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = adminlogin (w)
    admin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_adminlogin():
    global w
    w.destroy()
    w = None


class adminlogin:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("366x294+455+150")
        top.title("adminlogin")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Adminpage = Frame(top)
        self.Adminpage.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Adminpage.configure(relief=GROOVE)
        self.Adminpage.configure(borderwidth="10")
        self.Adminpage.configure(relief=GROOVE)
        self.Adminpage.configure(background="#8f0fff")
        self.Adminpage.configure(highlightbackground="#d9d9d9")
        self.Adminpage.configure(highlightcolor="black")
        self.Adminpage.configure(width=365)

        self.Adminlogin = Label(self.Adminpage)
        self.Adminlogin.place(relx=0.25, rely=0.1, height=41, width=164)
        self.Adminlogin.configure(activebackground="#f9f9f9")
        self.Adminlogin.configure(activeforeground="")
        self.Adminlogin.configure(background="#8f0fff")
        self.Adminlogin.configure(disabledforeground="#a3a3a3")
        self.Adminlogin.configure(font=font9)
        self.Adminlogin.configure(foreground="black")
        self.Adminlogin.configure(highlightbackground="#d9d9d9")
        self.Adminlogin.configure(highlightcolor="black")
        self.Adminlogin.configure(text='''Admin Login''')

        self.username = Label(self.Adminpage)
        self.username.place(relx=0.08, rely=0.37, height=34, width=100)
        self.username.configure(activebackground="#f9f9f9")
        self.username.configure(activeforeground="black")
        self.username.configure(background="#8f0fff")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font=font10)
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(text='''Username''')

        self.password = Label(self.Adminpage)
        self.password.place(relx=0.03, rely=0.47, height=71, width=134)
        self.password.configure(activebackground="#f9f9f9")
        self.password.configure(activeforeground="black")
        self.password.configure(background="#8f0fff")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font=font10)
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(text='''Password''')

        self.enterusername = Entry(self.Adminpage)
        self.enterusername.place(relx=0.47, rely=0.41,height=20, relwidth=0.45)
        self.enterusername.configure(background="#e5e5e5")
        self.enterusername.configure(disabledforeground="#a3a3a3")
        self.enterusername.configure(font="TkFixedFont")
        self.enterusername.configure(foreground="#000000")
        self.enterusername.configure(highlightbackground="#d9d9d9")
        self.enterusername.configure(highlightcolor="black")
        self.enterusername.configure(insertbackground="black")
        self.enterusername.configure(selectbackground="#c4c4c4")
        self.enterusername.configure(selectforeground="#ffffff")

        self.fra39_ent43 = Entry(self.Adminpage)
        self.fra39_ent43.place(relx=0.0, rely=0.0,height=1, relwidth=0.0)
        self.fra39_ent43.configure(background="white")
        self.fra39_ent43.configure(disabledforeground="#a3a3a3")
        self.fra39_ent43.configure(font="TkFixedFont")
        self.fra39_ent43.configure(foreground="#000000")
        self.fra39_ent43.configure(highlightbackground="#d9d9d9")
        self.fra39_ent43.configure(highlightcolor="black")
        self.fra39_ent43.configure(insertbackground="black")
        self.fra39_ent43.configure(selectbackground="#c4c4c4")
        self.fra39_ent43.configure(selectforeground="black")

        self.enterpassword = Entry(self.Adminpage)
        self.enterpassword.place(relx=0.47, rely=0.57,height=20, relwidth=0.45)
        self.enterpassword.configure(background="#e5e5e5")
        self.enterpassword.configure(disabledforeground="#a3a3a3")
        self.enterpassword.configure(font="TkFixedFont")
        self.enterpassword.configure(foreground="#000000")
        self.enterpassword.configure(highlightbackground="#d9d9d9")
        self.enterpassword.configure(highlightcolor="black")
        self.enterpassword.configure(insertbackground="black")
        self.enterpassword.configure(selectbackground="#c4c4c4")
        self.enterpassword.configure(selectforeground="black")
        self.enterpassword.configure(show="$")

        self.Button2 = Button(self.Adminpage)
        self.Button2.place(relx=0.38, rely=0.75, height=34, width=67)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#8f0fff")
        self.Button2.configure(borderwidth="0")
        self.Button2.configure(command=admin_support.adminLoginValidation)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font10)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Login''')





if __name__ == '__main__':
   vp_start_gui()



