#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 28, 2018 08:05:11 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def dispatcher_button():
    print('AdminHome_support.dispatcher_button')
    import DispatcherRegistration
    DispatcherRegistration.vp_start_gui()
    import AdminHome
    AdminHome.vp_start_gui()

def logout_button():
    print('AdminHome_support.logout_button')
    ans = messagebox.askyesno("Admin Logout", "Are You Sure")
    if ans:
        destroy_window()

def product_button():
    print('AdminHome_support.product_button')
    destroy_window()
    import AdminAddProduct
    AdminAddProduct.vp_start_gui()
    import AdminHome
    AdminHome.vp_start_gui()

def sales_button():
    print('AdminHome_support.sales_button')
    pass

def stocker_button():
    print('AdminHome_support.stocker_button')
    sys.stdout.flush()
    import  StockerRegistration
    StockerRegistration.vp_start_gui()
   # import AdminHome
    #AdminHome.vp_start_gui()

def customer_button():
    print("cb")



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

from tkinter import messagebox
def logout_button():
    ans = messagebox.askyesno("Admin Logout","Logout Conformation")
    if ans:
        destroy_window()



if __name__ == '__main__':
    import AdminHome
    AdminHome.vp_start_gui()


