#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 13, 2018 05:50:49 PM


import sys
from tkinter import messagebox

from firebase import firebase as fb
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None



def adminLoginValidation():
    username = w.enterusername.get()
    password = w.enterpassword.get()
    if(username == ""):
        messagebox.showerror("Admin Login","Please Enter Your Username")
    else:
        if(password==""):
            messagebox.showerror("Admin Login","Please Enter Your Password")
        else:
            fire = fb.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant", None)
            result = fire.get("merchant","admin")
            if((result["username"] == username) and (result["password"]== password)):
                messagebox.showinfo("Admin Login", "Welcome")
                destroy_window()
                import AdminHome
                AdminHome.vp_start_gui()

            else:
                messagebox.showerror("Admin Login","Username Or Password Is Incorrect")


if __name__ == '__main__':
    import admin

    admin.vp_start_gui()


