#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 13, 2018 02:17:14 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import AdminHome_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = AdminHome_ (root)
    AdminHome_support.init(root, top)
    root.mainloop()

w = None
def create_AdminHome_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = AdminHome_ (w)
    AdminHome_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_AdminHome_():
    global w
    w.destroy()
    w = None


class AdminHome_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 15 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("318x475+315+130")
        top.title("AdminHome ")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=0.99)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#ac07f2")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=315)

        self.stocker = Button(self.Frame1)
        self.stocker.place(relx=0.21, rely=0.09, height=34, width=167)
        self.stocker.configure(activebackground="#d9d9d9")
        self.stocker.configure(activeforeground="#000000")
        self.stocker.configure(background="#ba97ae")
        self.stocker.configure(command=AdminHome_support.stocker_button)
        self.stocker.configure(disabledforeground="#a3a3a3")
        self.stocker.configure(font=font9)
        self.stocker.configure(foreground="#000000")
        self.stocker.configure(highlightbackground="#d9d9d9")
        self.stocker.configure(highlightcolor="black")
        self.stocker.configure(pady="0")
        self.stocker.configure(text='''Stocker''')

        self.dispatcher = Button(self.Frame1)
        self.dispatcher.place(relx=0.21, rely=0.24, height=34, width=167)
        self.dispatcher.configure(activebackground="#d9d9d9")
        self.dispatcher.configure(activeforeground="#000000")
        self.dispatcher.configure(background="#ba97ae")
        self.dispatcher.configure(command=AdminHome_support.dispatcher_button)
        self.dispatcher.configure(disabledforeground="#a3a3a3")
        self.dispatcher.configure(font=font9)
        self.dispatcher.configure(foreground="#000000")
        self.dispatcher.configure(highlightbackground="#d9d9d9")
        self.dispatcher.configure(highlightcolor="black")
        self.dispatcher.configure(pady="0")
        self.dispatcher.configure(text='''Dispatcher''')

        self.product = Button(self.Frame1)
        self.product.place(relx=0.21, rely=0.4, height=34, width=167)
        self.product.configure(activebackground="#d9d9d9")
        self.product.configure(activeforeground="#000000")
        self.product.configure(background="#ba97ae")
        self.product.configure(command=AdminHome_support.product_button)
        self.product.configure(disabledforeground="#a3a3a3")
        self.product.configure(font=font9)
        self.product.configure(foreground="#000000")
        self.product.configure(highlightbackground="#d9d9d9")
        self.product.configure(highlightcolor="black")
        self.product.configure(pady="0")
        self.product.configure(text='''Product''')

        self.sales = Button(self.Frame1)
        self.sales.place(relx=0.19, rely=0.69, height=34, width=167)
        self.sales.configure(activebackground="#d9d9d9")
        self.sales.configure(activeforeground="#000000")
        self.sales.configure(background="#ba97ae")
        self.sales.configure(command=AdminHome_support.sales_button)
        self.sales.configure(disabledforeground="#a3a3a3")
        self.sales.configure(font=font9)
        self.sales.configure(foreground="#000000")
        self.sales.configure(highlightbackground="#d9d9d9")
        self.sales.configure(highlightcolor="black")
        self.sales.configure(pady="0")
        self.sales.configure(text='''Sales''')

        self.Button1_4 = Button(self.Frame1)
        self.Button1_4.place(relx=0.21, rely=0.85, height=34, width=167)
        self.Button1_4.configure(activebackground="#d9d9d9")
        self.Button1_4.configure(activeforeground="#000000")
        self.Button1_4.configure(background="#ba97ae")
        self.Button1_4.configure(command=AdminHome_support.logout_button)
        self.Button1_4.configure(disabledforeground="#a3a3a3")
        self.Button1_4.configure(font=font9)
        self.Button1_4.configure(foreground="#000000")
        self.Button1_4.configure(highlightbackground="#d9d9d9")
        self.Button1_4.configure(highlightcolor="black")
        self.Button1_4.configure(pady="0")
        self.Button1_4.configure(text='''Logout''')

        self.product_1 = Button(self.Frame1)
        self.product_1.place(relx=0.21, rely=0.55, height=34, width=167)
        self.product_1.configure(activebackground="#d9d9d9")
        self.product_1.configure(activeforeground="#000000")
        self.product_1.configure(background="#ba97ae")
        self.product_1.configure(command=AdminHome_support.customer_button)
        self.product_1.configure(disabledforeground="#a3a3a3")
        self.product_1.configure(font=font9)
        self.product_1.configure(foreground="#000000")
        self.product_1.configure(highlightbackground="#d9d9d9")
        self.product_1.configure(highlightcolor="black")
        self.product_1.configure(pady="0")
        self.product_1.configure(text='''Customer''')






if __name__ == '__main__':
    vp_start_gui()



