#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 05, 2018 10:59:25 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DispatcherPassword_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = DispatcherPassword (root)
    DispatcherPassword_support.init(root, top)
    root.mainloop()

w = None
def create_DispatcherPassword(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = DispatcherPassword (w)
    DispatcherPassword_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_DispatcherPassword():
    global w
    w.destroy()
    w = None


class DispatcherPassword:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 11 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("496x447+419+131")
        top.title("Change Password")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#0cf4ae")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=495)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.23, rely=0.03, height=31, width=254)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#0cf4ae")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Change Password''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.04, rely=0.36, height=31, width=164)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#0cf4ae")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Enter Old Password''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.04, rely=0.51, height=31, width=164)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#0cf4ae")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font9)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Enter NewPassword''')

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.03, rely=0.67, height=31, width=154)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#0cf4ae")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font9)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Retype Password''')

        self.Old_password = Entry(self.Frame1)
        self.Old_password.place(relx=0.42, rely=0.36,height=30, relwidth=0.41)
        self.Old_password.configure(background="white")
        self.Old_password.configure(disabledforeground="#a3a3a3")
        self.Old_password.configure(font="TkFixedFont")
        self.Old_password.configure(foreground="#000000")
        self.Old_password.configure(highlightbackground="#d9d9d9")
        self.Old_password.configure(highlightcolor="black")
        self.Old_password.configure(insertbackground="black")
        self.Old_password.configure(selectbackground="#c4c4c4")
        self.Old_password.configure(selectforeground="black")

        self.New_password = Entry(self.Frame1)
        self.New_password.place(relx=0.42, rely=0.51,height=30, relwidth=0.41)
        self.New_password.configure(background="white")
        self.New_password.configure(disabledforeground="#a3a3a3")
        self.New_password.configure(font="TkFixedFont")
        self.New_password.configure(foreground="#000000")
        self.New_password.configure(highlightbackground="#d9d9d9")
        self.New_password.configure(highlightcolor="black")
        self.New_password.configure(insertbackground="black")
        self.New_password.configure(selectbackground="#c4c4c4")
        self.New_password.configure(selectforeground="black")

        self.retype_password = Entry(self.Frame1)
        self.retype_password.place(relx=0.42, rely=0.66, height=30
                , relwidth=0.41)
        self.retype_password.configure(background="white")
        self.retype_password.configure(disabledforeground="#a3a3a3")
        self.retype_password.configure(font="TkFixedFont")
        self.retype_password.configure(foreground="#000000")
        self.retype_password.configure(highlightbackground="#d9d9d9")
        self.retype_password.configure(highlightcolor="black")
        self.retype_password.configure(insertbackground="black")
        self.retype_password.configure(selectbackground="#c4c4c4")
        self.retype_password.configure(selectforeground="black")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.51, rely=0.84, height=34, width=107)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0cf4ae")
        self.Button1.configure(command=DispatcherPassword_support.Dispatcher_Password)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Submit''')



if __name__ == '__main__':
    vp_start_gui()



