#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 05, 2018 01:43:34 AM


import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def dispatcher_add_product():
    print('DispatcherHome_support.dispatcher_add_product')
    sys.stdout.flush()

def dispatcher_ch_pass():
    print('DispatcherHome_support.dispatcher_ch_pass')
    sys.stdout.flush()

def dispatcher_logout():
    print('DispatcherHome_support.dispatcher_logout')
    sys.stdout.flush()

def dispatcher_view_product():
    print('DispatcherHome_support.dispatcher_view_product')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def dispatcher_ch_pass():
    destroy_window()
    import DispatcherPassword
    DispatcherPassword.vp_start_gui()

def dispatcher_add_product():
    destroy_window()
    import AdminAddProduct
    AdminAddProduct.vp_start_gui()

def dispatcher_view_product():
    destroy_window()
    import ProductList
    ProductList.vp_start_gui()

def dispatcher_logout():
    ans = messagebox.askyesno("Logout","Logout Confirmation")
    if ans:
        destroy_window()


if __name__ == '__main__':
    import DispatcherHome
    DispatcherHome.vp_start_gui()


