#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 26, 2018 07:15:03 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError  :
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def open_admin():
    destroy_window()
    import admin
    admin.vp_start_gui()

def open_dispatcher_login():
    destroy_window()
    import dispatcherlogin
    dispatcherlogin.vp_start_gui()
     #   print("dispatcher")

def open_stockerlogin():
    destroy_window()
    import stockerlogin
   # print("stocker")
    stockerlogin.vp_start_gui()

