#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 15, 2018 01:10:16 PM

import sys
from tkinter import messagebox

import fire as fire

import ProductList_support
from firebase import firebase

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ProductList_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Product_List (root)
    ProductList_support.init(root, top)
    root.mainloop()

w = None
def create_Product_List(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Product_List (w)
    ProductList_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Product_List():
    global w
    w.destroy()
    w = None


class Product_List:
    def __init__(self, top=None, font10=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("958x450+333+146")
        top.title("Product List")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.03, relheight=0.94, relwidth=0.99)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#07deed")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=945)


        fire = firebase.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/product",None)
        result = fire.get("product",None)
        if result == None:
            messagebox.showinfo("product List","No Products Available")
        else:
            no_of_rows = len(result.keys())
            rows = []
            #for i in range(no_of_rows):
            counter = 0
            for i in result:
                cols = []
                l = Label(self.Frame1,width=15)
                l.configure(font=font10)
                l.grid(row=counter, column=0, sticky=NSEW)
                l.configure(text=i)
                dt = result[i].values()
                val = []
                for x in dt:
                    val.append(x)
                #print(val)
                for inner in range(1,4):
                    l1 = Label(self.Frame1, width=15)
                    l1.configure(font=font10)
                    l1.grid(row=counter, column=inner, sticky=NSEW)
                    l1.configure(text=val[inner-1])
                    cols.append(l1)
                counter+=1
            rows.append(l)


if __name__ == '__main__':
    vp_start_gui()



