#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 03:21:19 AM


import sys
from tkinter import messagebox
from firebase import  firebase as fb


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import stockerlogin
    stockerlogin.vp_start_gui()

idno=" "
def stocker_login():
    global idno
    idno = w.stocker_name.get()
    password = w.stocker_password.get()
    if(idno == ""):
        messagebox.showerror("Stocker Login","Please Enter Username")
    else:
        if(password == ""):
            messagebox.showerror("Stocker Login","Please Enter Password")
        else:
            fire = fb.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/employee/stocker",None)
            result = fire.get("stocker",idno)
            if result != None:
                if result["password"] == password:
                    destroy_window()
                    import StockerHome
                    StockerHome.vp_start_gui()
                else:
                    messagebox.showerror("stocker login","Invalid Password")
            else:
                messagebox.showerror("stocker login","Username or Password Is Incorrect")

    return idno
