#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 13, 2018 01:59:46 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import stockerlogin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = stockerlogin_ (root)
    stockerlogin_support.init(root, top)
    root.mainloop()

w = None
def create_stockerlogin_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = stockerlogin_ (w)
    stockerlogin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_stockerlogin_():
    global w
    w.destroy()
    w = None


class stockerlogin_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 15 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("418x319+368+142")
        top.title("stockerlogin ")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.03, relheight=0.96, relwidth=0.97)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#0cf4ae")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=405)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.09, rely=0.29, height=64, width=92)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#0cf4ae")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Idno''')

        self.Label1_1 = Label(self.Frame1)
        self.Label1_1.place(relx=0.11, rely=0.49, height=51, width=94)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#0cf4ae")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font9)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Password''')

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.53, rely=0.72, height=44, width=87)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0cf4ae")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=stockerlogin_support.stocker_login)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Login''')

        self.stocker_name = Entry(self.Frame1)
        self.stocker_name.place(relx=0.42, rely=0.38,height=20, relwidth=0.4)
        self.stocker_name.configure(background="white")
        self.stocker_name.configure(borderwidth="0")
        self.stocker_name.configure(disabledforeground="#a3a3a3")
        self.stocker_name.configure(font="TkFixedFont")
        self.stocker_name.configure(foreground="#000000")
        self.stocker_name.configure(highlightbackground="#d9d9d9")
        self.stocker_name.configure(highlightcolor="black")
        self.stocker_name.configure(insertbackground="black")
        self.stocker_name.configure(selectbackground="#c4c4c4")
        self.stocker_name.configure(selectforeground="black")

        self.stocker_password = Entry(self.Frame1)
        self.stocker_password.place(relx=0.42, rely=0.55, height=20
                , relwidth=0.4)
        self.stocker_password.configure(background="white")
        self.stocker_password.configure(borderwidth="0")
        self.stocker_password.configure(disabledforeground="#a3a3a3")
        self.stocker_password.configure(font="TkFixedFont")
        self.stocker_password.configure(foreground="#000000")
        self.stocker_password.configure(highlightbackground="#d9d9d9")
        self.stocker_password.configure(highlightcolor="black")
        self.stocker_password.configure(insertbackground="black")
        self.stocker_password.configure(selectbackground="#c4c4c4")
        self.stocker_password.configure(selectforeground="black")
        self.stocker_password.configure(show="*")

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.25, rely=0.09, height=43, width=182)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#0cf4ae")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Stocker Login''')






if __name__ == '__main__':
    vp_start_gui()



