#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 05, 2018 01:45:32 AM
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def stocker_logout():
    if messagebox.askyesno("Logout","Are You Sure"):
        destroy_window()


def stocker_view_product():
    print("View Product")

def stocker_add_product():
    print("Add Product")

def stocker_change_password():
    print("Change Pass")



def stocker_view_product():
    destroy_window()
    import ProductList
    ProductList.vp_start_gui()
    destroy_window()
    import StockerHome
    StockerHome.vp_start_gui()

def stocker_add_product():
    destroy_window()
    import AdminAddProduct
    AdminAddProduct.vp_start_gui()
    import StockerHome
    StockerHome.vp_start_gui()

def stocker_change_password():
    destroy_window()
    import ChangePassword
    ChangePassword.vp_start_gui()
#if __name__ == '__main__':
  #  vp_start_gui()

