#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 19, 2018 04:55:28 PM


import sys
from tkinter import messagebox
from firebase import firebase as fb

import AdminHome

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def adminLoginValidation():
    username = w.admin_username.get()
    password = w.admin_password.get()
    if(username == ""):
        messagebox.showerror("Admin Login","Please Enter Username")
    else:
        if(password == ""):
            messagebox.showerror("Admin Login","Please Enter Password")
        else:
            fire = fb.FirebaseApplication("https://merchant-application-e1450.firebaseio.com/",None)
            result = fire.get("merchant","admin")
            if(result["username"] == username):
                if(result["password"] == password):
                    destroy_window()
                    AdminHome.vp_start_gui()

                else:
                    messagebox.showerror("Admin Login", "Invalid Password")
                    #w.admin_password.set("")
            else:
                messagebox.showerror("Admin Login","Invalid Username")






#
# if __name__ == '__main__':
#     import AdminLogin
#     AdminLogin.vp_start_gui()


