#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 27, 2018 03:26:30 PM


import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def dispatcher_change_password():
    print("dis Change")

def dispatcher_View_Order():
    print("dis order")

def dispatcher_Sent_Orders():
    print(" sent")

def dispatcher_logout():
    if messagebox.askyesno("Logout","Conformation"):
        destroy_window()