#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 26, 2018 06:21:37 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DispatcherRegistration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Dispatcher_Employee (root)
    DispatcherRegistration_support.init(root, top)
    root.mainloop()

w = None
def create_Stocker_Employee(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Dispatcher_Employee(w)
    DispatcherRegistration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Stocker_Employee():
    global w
    w.destroy()
    w = None


class Dispatcher_Employee:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family {Courier New} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 15 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("711x450+73+120")
        top.title("Dispatcher Employee")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.02, relheight=0.94, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#ffca85")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=695)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.03, rely=0.02, height=41, width=284)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffca85")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Dispatcher Registration''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.01, rely=0.16, height=31, width=84)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#ffca85")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''IDNO''')

        self.stocker_idno = Label(self.Frame1)
        self.stocker_idno.place(relx=0.19, rely=0.16, height=31, width=84)
        self.stocker_idno.configure(activebackground="#f9f9f9")
        self.stocker_idno.configure(activeforeground="black")
        self.stocker_idno.configure(background="#ffca85")
        self.stocker_idno.configure(disabledforeground="#a3a3a3")
        self.stocker_idno.configure(font=font9)
        self.stocker_idno.configure(foreground="#000000")
        self.stocker_idno.configure(highlightbackground="#d9d9d9")
        self.stocker_idno.configure(highlightcolor="black")
        self.stocker_idno.configure(text='''.....''')
        idno = DispatcherRegistration_support.dispatcher_autogen_id()
        self.stocker_idno.configure(text=idno)

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.01, rely=0.27, height=31, width=84)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#ffca85")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font9)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''NAME''')

        self.stocker_name = Entry(self.Frame1)
        self.stocker_name.place(relx=0.18, rely=0.28,height=30, relwidth=0.25)
        self.stocker_name.configure(background="white")
        self.stocker_name.configure(borderwidth="0")
        self.stocker_name.configure(disabledforeground="#a3a3a3")
        self.stocker_name.configure(font=font10)
        self.stocker_name.configure(foreground="#000000")
        self.stocker_name.configure(highlightbackground="#d9d9d9")
        self.stocker_name.configure(highlightcolor="black")
        self.stocker_name.configure(insertbackground="black")
        self.stocker_name.configure(selectbackground="#c4c4c4")
        self.stocker_name.configure(selectforeground="black")

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.01, rely=0.38, height=31, width=84)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#ffca85")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font9)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''PHONE''')

        self.stocker_phone = Entry(self.Frame1)
        self.stocker_phone.place(relx=0.18, rely=0.38,height=30, relwidth=0.25)
        self.stocker_phone.configure(background="white")
        self.stocker_phone.configure(borderwidth="0")
        self.stocker_phone.configure(disabledforeground="#a3a3a3")
        self.stocker_phone.configure(font=font10)
        self.stocker_phone.configure(foreground="#000000")
        self.stocker_phone.configure(highlightbackground="#d9d9d9")
        self.stocker_phone.configure(highlightcolor="black")
        self.stocker_phone.configure(insertbackground="black")
        self.stocker_phone.configure(selectbackground="#c4c4c4")
        self.stocker_phone.configure(selectforeground="black")

        self.Label2_4 = Label(self.Frame1)
        self.Label2_4.place(relx=-0.01, rely=0.49, height=31, width=124)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#ffca85")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(font=font9)
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''PASSWORD''')

        self.stocker_password = Entry(self.Frame1)
        self.stocker_password.place(relx=0.18, rely=0.49, height=30
                , relwidth=0.25)
        self.stocker_password.configure(background="white")
        self.stocker_password.configure(borderwidth="0")
        self.stocker_password.configure(disabledforeground="#a3a3a3")
        self.stocker_password.configure(font=font10)
        self.stocker_password.configure(foreground="#000000")
        self.stocker_password.configure(highlightbackground="#d9d9d9")
        self.stocker_password.configure(highlightcolor="black")
        self.stocker_password.configure(insertbackground="black")
        self.stocker_password.configure(selectbackground="#c4c4c4")
        self.stocker_password.configure(selectforeground="black")
        self.stocker_password.configure(show="*")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.22, rely=0.56, height=54, width=117)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffca85")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=DispatcherRegistration_support.save_dispatcher)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.5, rely=0.02, relheight=0.95, relwidth=0.01)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="1")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#000000")
        self.Frame2.configure(width=5)

        self.Label1_1 = Label(self.Frame1)
        self.Label1_1.place(relx=0.55, rely=0.02, height=41, width=284)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#ffca85")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font11)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''View Dispatcher''')

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.53, rely=0.17, height=31, width=84)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#ffca85")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font9)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''IDNO''')

        self.view_stocker_id = Entry(self.Frame1)
        self.view_stocker_id.place(relx=0.65, rely=0.17, height=30
                , relwidth=0.25)
        self.view_stocker_id.configure(background="white")
        self.view_stocker_id.configure(borderwidth="0")
        self.view_stocker_id.configure(disabledforeground="#a3a3a3")
        self.view_stocker_id.configure(font=font10)
        self.view_stocker_id.configure(foreground="#000000")
        self.view_stocker_id.configure(highlightbackground="#d9d9d9")
        self.view_stocker_id.configure(highlightcolor="black")
        self.view_stocker_id.configure(insertbackground="black")
        self.view_stocker_id.configure(selectbackground="#c4c4c4")
        self.view_stocker_id.configure(selectforeground="black")

        self.Button1_4 = Button(self.Frame1)
        self.Button1_4.place(relx=0.68, rely=0.26, height=54, width=117)
        self.Button1_4.configure(activebackground="#d9d9d9")
        self.Button1_4.configure(activeforeground="#000000")
        self.Button1_4.configure(background="#ffca85")
        self.Button1_4.configure(borderwidth="0")
        self.Button1_4.configure(command=DispatcherRegistration_support.view_dispatcher)
        self.Button1_4.configure(disabledforeground="#a3a3a3")
        self.Button1_4.configure(font=font9)
        self.Button1_4.configure(foreground="#000000")
        self.Button1_4.configure(highlightbackground="#d9d9d9")
        self.Button1_4.configure(highlightcolor="black")
        self.Button1_4.configure(pady="0")
        self.Button1_4.configure(text='''Show''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.53, rely=0.4, height=31, width=84)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#ffca85")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font9)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''NAME''')

        self.view_stocker_name = Label(self.Frame1)
        self.view_stocker_name.place(relx=0.69, rely=0.4, height=31, width=184)
        self.view_stocker_name.configure(activebackground="#f9f9f9")
        self.view_stocker_name.configure(activeforeground="black")
        self.view_stocker_name.configure(background="#ffca85")
        self.view_stocker_name.configure(disabledforeground="#a3a3a3")
        self.view_stocker_name.configure(font=font9)
        self.view_stocker_name.configure(foreground="#000000")
        self.view_stocker_name.configure(highlightbackground="#d9d9d9")
        self.view_stocker_name.configure(highlightcolor="black")
        self.view_stocker_name.configure(text='''........................''')
        self.view_stocker_name.configure(width=184)

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.53, rely=0.54, height=31, width=84)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#ffca85")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font9)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''PHONE''')

        self.view_stockter_cno = Label(self.Frame1)
        self.view_stockter_cno.place(relx=0.69, rely=0.55, height=31, width=184)
        self.view_stockter_cno.configure(activebackground="#f9f9f9")
        self.view_stockter_cno.configure(activeforeground="black")
        self.view_stockter_cno.configure(background="#ffca85")
        self.view_stockter_cno.configure(disabledforeground="#a3a3a3")
        self.view_stockter_cno.configure(font=font9)
        self.view_stockter_cno.configure(foreground="#000000")
        self.view_stockter_cno.configure(highlightbackground="#d9d9d9")
        self.view_stockter_cno.configure(highlightcolor="black")
        self.view_stockter_cno.configure(text='''........................''')
        self.view_stockter_cno.configure(width=184)

        self.Button1_5 = Button(self.Frame1)
        self.Button1_5.place(relx=0.55, rely=0.66, height=54, width=117)
        self.Button1_5.configure(activebackground="#d9d9d9")
        self.Button1_5.configure(activeforeground="#000000")
        self.Button1_5.configure(background="#22ff00")
        self.Button1_5.configure(borderwidth="0")
        self.Button1_5.configure(command=DispatcherRegistration_support.delete_dispatcher)
        self.Button1_5.configure(disabledforeground="#a3a3a3")
        self.Button1_5.configure(font=font9)
        self.Button1_5.configure(foreground="#000000")
        self.Button1_5.configure(highlightbackground="#d9d9d9")
        self.Button1_5.configure(highlightcolor="black")
        self.Button1_5.configure(pady="0")
        self.Button1_5.configure(text='''Delete''')







