#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 27, 2018 03:14:01 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DispatcherLogin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Dispatcher_Login (root)
    DispatcherLogin_support.init(root, top)
    root.mainloop()

w = None
def create_Admin_Login(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Dispatcher_Login (w)
    DispatcherLogin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Admin_Login():
    global w
    w.destroy()
    w = None


class Dispatcher_Login:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family {Courier New} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 15 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("478x332+270+113")
        top.title("Dispatcher Login")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.03, relheight=0.95, relwidth=0.95)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#ffca85")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=455)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.33, rely=0.1, height=43, width=200)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffca85")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Dispatcher Login''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.13, rely=0.32, height=34, width=100)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#ffca85")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Idno''')

        self.admin_username = Entry(self.Frame1)
        self.admin_username.place(relx=0.41, rely=0.33,height=30, relwidth=0.4)
        self.admin_username.configure(background="white")
        self.admin_username.configure(disabledforeground="#a3a3a3")
        self.admin_username.configure(font=font10)
        self.admin_username.configure(foreground="#000000")
        self.admin_username.configure(highlightbackground="#d9d9d9")
        self.admin_username.configure(highlightcolor="black")
        self.admin_username.configure(insertbackground="black")
        self.admin_username.configure(selectbackground="#c4c4c4")
        self.admin_username.configure(selectforeground="black")

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.13, rely=0.51, height=34, width=100)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#ffca85")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font9)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Password''')

        self.admin_password = Entry(self.Frame1)
        self.admin_password.place(relx=0.41, rely=0.51,height=30, relwidth=0.4)
        self.admin_password.configure(background="white")
        self.admin_password.configure(disabledforeground="#a3a3a3")
        self.admin_password.configure(font=font10)
        self.admin_password.configure(foreground="#000000")
        self.admin_password.configure(highlightbackground="#d9d9d9")
        self.admin_password.configure(highlightcolor="black")
        self.admin_password.configure(insertbackground="black")
        self.admin_password.configure(selectbackground="#c4c4c4")
        self.admin_password.configure(selectforeground="black")
        self.admin_password.configure(show="*")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.42, rely=0.7, height=34, width=187)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffca85")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=DispatcherLogin_support.dispatcherLoginValidation)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Login''')








