#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 27, 2018 02:27:42 PM


import sys
from tkinter import messagebox
from firebase import firebase as fb

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
import Stocker_Home
def Stocker_validation():
    idno = w.Admin_username.get()
    password = w.Admin_password.get()
    if(idno == ""):
        messagebox.showerror("Stocker Login","Please Enter Username")
    else:
        if(password == ""):
            messagebox.showerror("Stocker Login","Please Enter Password")
        else:
            fire = fb.FirebaseApplication("https://python-project-2d5d6.firebaseio.com/merchant/employee/stocker",None)
            result = fire.get("stocker", idno)
            if result != None:
                if result["password"] == password:
                    destroy_window()
                    Stocker_Home.vp_start_gui()
                else:
                    messagebox.showerror("stocker login","Invalid Password")
            else:
                messagebox.showerror("stocker login","Username or Password Is Incorrect")

def Stocker_Cancel():
    destroy_window()


