#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 01:10:45 AM

import sys

import self as self

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DispatcherRegistration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = DispatcherRegistration (root)
    DispatcherRegistration_support.init(root, top)
    root.mainloop()

w = None
def create_DispatcherRegistration (root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = DispatcherRegistration (w)
    DispatcherRegistration_support.init(w, top, *args, **kwargs)
    return (w, top)

def distroy_DispatcherRegistration():
    global w
    w.destroy()
    w = None


class DispatcherRegistration:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Courier New} -size 13 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("713x399+297+118")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")


       self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#0cf4ae")
        self.Frame1.configure(width=715)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.05, rely=0.05, height=43, width=269)
        self.Label1.configure(background="#0cf4ae")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10zzzzzzz)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Stocker Registration''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.05, rely=0.27, height=34, width=48)
        self.Label2.configure(background="#0cf4ae")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Idno''')

        self.Lable3 = Label(self.Frame1)
        self.Lable3.place(relx=0.2, rely=0.27, height=34, width=76)
        self.Lable3.configure(background="#0cf4ae")
        self.Lable3.configure(disabledforeground="#a3a3a3")
        self.Lable3.configure(font=font10)
        self.Lable3.configure(foreground="#000000")
        self.Lable3.configure(text='''...........''')
        idno=StockerRegistration_support.sautogen_id()
        self.Lable3.configure(text=idno)

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.04, rely=0.42, height=34, width=62)
        self.Label4.configure(background="#0cf4ae")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font10)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Name''')

        self.stocker_username = Entry(self.Frame1)
        self.stocker_username.place(relx=0.2, rely=0.44, height=22
                , relwidth=0.24)
        self.stocker_username.configure(background="white")
        self.stocker_username.configure(borderwidth="0")
        self.stocker_username.configure(disabledforeground="#a3a3a3")
        self.stocker_username.configure(font=font12)
        self.stocker_username.configure(foreground="#000000")
        self.stocker_username.configure(insertbackground="black")
        self.stocker_username.configure(width=172)

        self.Label5 = Label(self.Frame1)
        self.Label5.place(relx=0.04, rely=0.57, height=34, width=65)
        self.Label5.configure(background="#0cf4ae")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font10)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Phone''')

        self.stocker_phone = Entry(self.Frame1)
        self.stocker_phone.place(relx=0.2, rely=0.59,height=22, relwidth=0.24)
        self.stocker_phone.configure(background="white")
        self.stocker_phone.configure(borderwidth="0")
        self.stocker_phone.configure(disabledforeground="#a3a3a3")
        self.stocker_phone.configure(font=font12)
        self.stocker_phone.configure(foreground="#000000")
        self.stocker_phone.configure(highlightbackground="#d9d9d9")
        self.stocker_phone.configure(highlightcolor="black")
        self.stocker_phone.configure(insertbackground="black")
        self.stocker_phone.configure(selectbackground="#c4c4c4")
        self.stocker_phone.configure(selectforeground="black")

        self.Label6 = Label(self.Frame1)
        self.Label6.place(relx=0.03, rely=0.72, height=34, width=95)
        self.Label6.configure(background="#0cf4ae")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font10)
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Password''')

        self.stocker_password = Entry(self.Frame1)
        self.stocker_password.place(relx=0.2, rely=0.74, height=22
                , relwidth=0.24)
        self.stocker_password.configure(background="white")
        self.stocker_password.configure(borderwidth="0")
        self.stocker_password.configure(disabledforeground="#a3a3a3")
        self.stocker_password.configure(font=font12)
        self.stocker_password.configure(foreground="#000000")
        self.stocker_password.configure(highlightbackground="#d9d9d9")
        self.stocker_password.configure(highlightcolor="black")
        self.stocker_password.configure(insertbackground="black")
        self.stocker_password.configure(selectbackground="#c4c4c4")
        self.stocker_password.configure(selectforeground="black")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.32, rely=0.86, height=34, width=77)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0cf4ae")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=StockerRegistration_support.save_stocker)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')
        self.Button1.configure(width=77)

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.48, rely=0.03, relheight=0.95, relwidth=0.0)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#0a0a0a")
        self.Frame2.configure(width=-25)

        self.Label1_3 = Label(self.Frame1)
        self.Label1_3.place(relx=0.55, rely=0.05, height=43, width=269)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#0cf4ae")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font10)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''View  Stocker''')

        self.Label2_4 = Label(self.Frame1)
        self.Label2_4.place(relx=0.52, rely=0.27, height=34, width=48)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#0cf4ae")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(font=font10)
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Idno''')

        self.stocker_idno = Entry(self.Frame1)
        self.stocker_idno.place(relx=0.64, rely=0.29,height=22, relwidth=0.24)
        self.stocker_idno.configure(background="white")
        self.stocker_idno.configure(borderwidth="0")
        self.stocker_idno.configure(disabledforeground="#a3a3a3")
        self.stocker_idno.configure(font=font12)
        self.stocker_idno.configure(foreground="#000000")
        self.stocker_idno.configure(highlightbackground="#d9d9d9")
        self.stocker_idno.configure(highlightcolor="black")
        self.stocker_idno.configure(insertbackground="black")
        self.stocker_idno.configure(selectbackground="#c4c4c4")
        self.stocker_idno.configure(selectforeground="black")

        self.Button1_6 = Button(self.Frame1)
        self.Button1_6.place(relx=0.71, rely=0.38, height=34, width=77)
        self.Button1_6.configure(activebackground="#d9d9d9")
        self.Button1_6.configure(activeforeground="#000000")
        self.Button1_6.configure(background="#0cf4ae")
        self.Button1_6.configure(borderwidth="0")
        self.Button1_6.configure(command=StockerRegistration_support.view_stocker)
        self.Button1_6.configure(disabledforeground="#a3a3a3")
        self.Button1_6.configure(font=font10)
        self.Button1_6.configure(foreground="#000000")
        self.Button1_6.configure(highlightbackground="#d9d9d9")
        self.Button1_6.configure(highlightcolor="black")
        self.Button1_6.configure(pady="0")
        self.Button1_6.configure(text='''View''')

        self.Label4_7 = Label(self.Frame1)
        self.Label4_7.place(relx=0.52, rely=0.53, height=34, width=62)
        self.Label4_7.configure(activebackground="#f9f9f9")
        self.Label4_7.configure(activeforeground="black")
        self.Label4_7.configure(background="#0cf4ae")
        self.Label4_7.configure(disabledforeground="#a3a3a3")
        self.Label4_7.configure(font=font10)
        self.Label4_7.configure(foreground="#000000")
        self.Label4_7.configure(highlightbackground="#d9d9d9")
        self.Label4_7.configure(highlightcolor="black")
        self.Label4_7.configure(text='''Name''')

        self.Label5_8 = Label(self.Frame1)
        self.Label5_8.place(relx=0.52, rely=0.69, height=34, width=65)
        self.Label5_8.configure(activebackground="#f9f9f9")
        self.Label5_8.configure(activeforeground="black")
        self.Label5_8.configure(background="#0cf4ae")
        self.Label5_8.configure(disabledforeground="#a3a3a3")
        self.Label5_8.configure(font=font10)
        self.Label5_8.configure(foreground="#000000")
        self.Label5_8.configure(highlightbackground="#d9d9d9")
        self.Label5_8.configure(highlightcolor="black")
        self.Label5_8.configure(text='''Phone''')

        self.Label7 = Label(self.Frame1)
        self.Label7.place(relx=0.73, rely=0.53, height=34, width=76)
        self.Label7.configure(background="#0cf4ae")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font=font10)
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''................''')

        self.Label8 = Label(self.Frame1)
        self.Label8.place(relx=0.64, rely=0.68, height=34, width=206)
        self.Label8.configure(background="#0cf4ae")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(font=font10)
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''..................''')
        self.Label8.configure(width=206)

        self.Button1_9 = Button(self.Frame1)
        self.Button1_9.place(relx=0.73, rely=0.85, height=34, width=77)
        self.Button1_9.configure(activebackground="#d9d9d9")
        self.Button1_9.configure(activeforeground="#000000")
        self.Button1_9.configure(background="#0cf4ae")
        self.Button1_9.configure(borderwidth="0")
        self.Button1_9.configure(command=DispatcherRegistration_support.delete_stocker)
        self.Button1_9.configure(disabledforeground="#a3a3a3")
        self.Button1_9.configure(font=font10)
        self.Button1_9.configure(foreground="#000000")
        self.Button1_9.configure(highlightbackground="#d9d9d9")
        self.Button1_9.configure(highlightcolor="black")
        self.Button1_9.configure(pady="0")
        self.Button1_9.configure(text='''Delete''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()



