#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 25, 2018 07:48:08 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import EmployeeHome_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Employee_Home (root)
    EmployeeHome_support.init(root, top)
    root.mainloop()

w = None
def create_Employee_Home(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Employee_Home (w)
    EmployeeHome_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Employee_Home():
    global w
    w.destroy()
    w = None


class Employee_Home:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 18 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("600x450+429+142")
        top.title("Employee Home")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.02, relheight=0.97, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#21ddea")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=585)

        self.stocker_button = Button(self.Frame1)
        self.stocker_button.place(relx=0.07, rely=0.07, height=34, width=97)
        self.stocker_button.configure(activebackground="#d9d9d9")
        self.stocker_button.configure(activeforeground="#000000")
        self.stocker_button.configure(background="#21ddea")
        self.stocker_button.configure(borderwidth="0")
        self.stocker_button.configure(disabledforeground="#a3a3a3")
        self.stocker_button.configure(font=font11)
        self.stocker_button.configure(foreground="#000000")
        self.stocker_button.configure(highlightbackground="#d9d9d9")
        self.stocker_button.configure(highlightcolor="black")
        self.stocker_button.configure(pady="0")
        self.stocker_button.configure(text='''Stocker''')

        self.dispatcher_button = Button(self.Frame1)
        self.dispatcher_button.place(relx=0.32, rely=0.07, height=34, width=117)
        self.dispatcher_button.configure(activebackground="#d9d9d9")
        self.dispatcher_button.configure(activeforeground="#000000")
        self.dispatcher_button.configure(background="#21ddea")
        self.dispatcher_button.configure(borderwidth="0")
        self.dispatcher_button.configure(disabledforeground="#a3a3a3")
        self.dispatcher_button.configure(font=font11)
        self.dispatcher_button.configure(foreground="#000000")
        self.dispatcher_button.configure(highlightbackground="#d9d9d9")
        self.dispatcher_button.configure(highlightcolor="black")
        self.dispatcher_button.configure(pady="0")
        self.dispatcher_button.configure(text='''Dispatcher''')

        self.stocker_reg_frame = Frame(self.Frame1)
        self.stocker_reg_frame.place(relx=0.02, rely=0.18, relheight=0.77
                , relwidth=0.49)
        self.stocker_reg_frame.configure(relief=GROOVE)
        self.stocker_reg_frame.configure(borderwidth="2")
        self.stocker_reg_frame.configure(relief=GROOVE)
        self.stocker_reg_frame.configure(background="#d811cb")
        self.stocker_reg_frame.configure(highlightbackground="#d9d9d9")
        self.stocker_reg_frame.configure(highlightcolor="black")
        self.stocker_reg_frame.configure(width=285)

        self.Stocker_registration = Label(self.stocker_reg_frame)
        self.Stocker_registration.place(relx=0.0, rely=0.03, height=41
                , width=274)
        self.Stocker_registration.configure(activebackground="#f9f9f9")
        self.Stocker_registration.configure(activeforeground="black")
        self.Stocker_registration.configure(background="#d811cb")
        self.Stocker_registration.configure(disabledforeground="#a3a3a3")
        self.Stocker_registration.configure(font=font9)
        self.Stocker_registration.configure(foreground="#000000")
        self.Stocker_registration.configure(highlightbackground="#d9d9d9")
        self.Stocker_registration.configure(highlightcolor="black")
        self.Stocker_registration.configure(text='''Stocker Registration''')

        self.Label2 = Label(self.stocker_reg_frame)
        self.Label2.place(relx=0.04, rely=0.21, height=31, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d324811cb")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Idno''')

        self.Label2_3 = Label(self.stocker_reg_frame)
        self.Label2_3.place(relx=0.04, rely=0.34, height=31, width=74)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#d811cb")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font11)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Name''')

        self.Label2_4 = Label(self.stocker_reg_frame)
        self.Label2_4.place(relx=0.0, rely=0.49, height=31, width=94)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#d811cb")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(font=font11)
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Contact''')

        self.Label2_5 = Label(self.stocker_reg_frame)
        self.Label2_5.place(relx=0.0, rely=0.64, height=31, width=94)
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(activeforeground="black")
        self.Label2_5.configure(background="#d811cb")
        self.Label2_5.configure(disabledforeground="#a3a3a3")
        self.Label2_5.configure(font=font11)
        self.Label2_5.configure(foreground="#000000")
        self.Label2_5.configure(highlightbackground="#d9d9d9")
        self.Label2_5.configure(highlightcolor="black")
        self.Label2_5.configure(text='''Password''')

        self.Button2 = Button(self.stocker_reg_frame)
        self.Button2.place(relx=0.11, rely=0.81, height=34, width=77)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d811cb")
        self.Button2.configure(borderwidth="0")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font11)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Save''')

        self.stocker_idno = Entry(self.stocker_reg_frame)
        self.stocker_idno.place(relx=0.35, rely=0.22,height=30, relwidth=0.61)
        self.stocker_idno.configure(background="white")
        self.stocker_idno.configure(disabledforeground="#a3a3a3")
        self.stocker_idno.configure(font="TkFixedFont")
        self.stocker_idno.configure(foreground="#000000")
        self.stocker_idno.configure(highlightbackground="#d9d9d9")
        self.stocker_idno.configure(highlightcolor="black")
        self.stocker_idno.configure(insertbackground="black")
        self.stocker_idno.configure(selectbackground="#c4c4c4")
        self.stocker_idno.configure(selectforeground="black")

        self.stocker_name = Entry(self.stocker_reg_frame)
        self.stocker_name.place(relx=0.35, rely=0.36,height=30, relwidth=0.61)
        self.stocker_name.configure(background="white")
        self.stocker_name.configure(disabledforeground="#a3a3a3")
        self.stocker_name.configure(font=font10)
        self.stocker_name.configure(foreground="#000000")
        self.stocker_name.configure(highlightbackground="#d9d9d9")
        self.stocker_name.configure(highlightcolor="black")
        self.stocker_name.configure(insertbackground="black")
        self.stocker_name.configure(selectbackground="#c4c4c4")
        self.stocker_name.configure(selectforeground="black")

        self.stocker_cno = Entry(self.stocker_reg_frame)
        self.stocker_cno.place(relx=0.35, rely=0.5,height=30, relwidth=0.61)
        self.stocker_cno.configure(background="white")
        self.stocker_cno.configure(disabledforeground="#a3a3a3")
        self.stocker_cno.configure(font=font10)
        self.stocker_cno.configure(foreground="#000000")
        self.stocker_cno.configure(highlightbackground="#d9d9d9")
        self.stocker_cno.configure(highlightcolor="black")
        self.stocker_cno.configure(insertbackground="black")
        self.stocker_cno.configure(selectbackground="#c4c4c4")
        self.stocker_cno.configure(selectforeground="black")

        self.stocker_password = Entry(self.stocker_reg_frame)
        self.stocker_password.place(relx=0.35, rely=0.65, height=30
                , relwidth=0.61)
        self.stocker_password.configure(background="white")
        self.stocker_password.configure(disabledforeground="#a3a3a3")
        self.stocker_password.configure(font=font10)
        self.stocker_password.configure(foreground="#000000")
        self.stocker_password.configure(highlightbackground="#d9d9d9")
        self.stocker_password.configure(highlightcolor="black")
        self.stocker_password.configure(insertbackground="black")
        self.stocker_password.configure(selectbackground="#c4c4c4")
        self.stocker_password.configure(selectforeground="black")
        self.stocker_password.configure(show="*")

        self.Dispatcher_reg_frame = Frame(self.Frame1)
        self.Dispatcher_reg_frame.place(relx=0.5, rely=0.18, relheight=0.77
                , relwidth=0.49)
        self.Dispatcher_reg_frame.configure(relief=GROOVE)
        self.Dispatcher_reg_frame.configure(borderwidth="2")
        self.Dispatcher_reg_frame.configure(relief=GROOVE)
        self.Dispatcher_reg_frame.configure(background="#b0d852")
        self.Dispatcher_reg_frame.configure(highlightbackground="#d9d9d9")
        self.Dispatcher_reg_frame.configure(highlightcolor="black")
        self.Dispatcher_reg_frame.configure(width=285)

        self.Dispatcher_registration = Label(self.Dispatcher_reg_frame)
        self.Dispatcher_registration.place(relx=0.02, rely=0.01, height=41
                , width=274)
        self.Dispatcher_registration.configure(activebackground="#f9f9f9")
        self.Dispatcher_registration.configure(activeforeground="black")
        self.Dispatcher_registration.configure(background="#b0d852")
        self.Dispatcher_registration.configure(disabledforeground="#a3a3a3")
        self.Dispatcher_registration.configure(font=font9)
        self.Dispatcher_registration.configure(foreground="#000000")
        self.Dispatcher_registration.configure(highlightbackground="#d9d9d9")
        self.Dispatcher_registration.configure(highlightcolor="black")
        self.Dispatcher_registration.configure(text='''Dispatcher Registration''')

        self.Label2_10 = Label(self.Dispatcher_reg_frame)
        self.Label2_10.place(relx=0.05, rely=0.2, height=31, width=74)
        self.Label2_10.configure(activebackground="#f9f9f9")
        self.Label2_10.configure(activeforeground="black")
        self.Label2_10.configure(background="#b0d852")
        self.Label2_10.configure(disabledforeground="#a3a3a3")
        self.Label2_10.configure(font=font11)
        self.Label2_10.configure(foreground="#000000")
        self.Label2_10.configure(highlightbackground="#d9d9d9")
        self.Label2_10.configure(highlightcolor="black")
        self.Label2_10.configure(text='''Idno''')

        self.Label2_11 = Label(self.Dispatcher_reg_frame)
        self.Label2_11.place(relx=0.05, rely=0.33, height=31, width=74)
        self.Label2_11.configure(activebackground="#f9f9f9")
        self.Label2_11.configure(activeforeground="black")
        self.Label2_11.configure(background="#b0d852")
        self.Label2_11.configure(disabledforeground="#a3a3a3")
        self.Label2_11.configure(font=font11)
        self.Label2_11.configure(foreground="#000000")
        self.Label2_11.configure(highlightbackground="#d9d9d9")
        self.Label2_11.configure(highlightcolor="black")
        self.Label2_11.configure(text='''Name''')

        self.Label2_12 = Label(self.Dispatcher_reg_frame)
        self.Label2_12.place(relx=0.04, rely=0.48, height=31, width=84)
        self.Label2_12.configure(activebackground="#f9f9f9")
        self.Label2_12.configure(activeforeground="black")
        self.Label2_12.configure(background="#b0d852")
        self.Label2_12.configure(disabledforeground="#a3a3a3")
        self.Label2_12.configure(font=font11)
        self.Label2_12.configure(foreground="#000000")
        self.Label2_12.configure(highlightbackground="#d9d9d9")
        self.Label2_12.configure(highlightcolor="black")
        self.Label2_12.configure(text='''Contact''')

        self.Label2_13 = Label(self.Dispatcher_reg_frame)
        self.Label2_13.place(relx=0.02, rely=0.64, height=31, width=94)
        self.Label2_13.configure(activebackground="#f9f9f9")
        self.Label2_13.configure(activeforeground="black")
        self.Label2_13.configure(background="#b0d852")
        self.Label2_13.configure(disabledforeground="#a3a3a3")
        self.Label2_13.configure(font=font11)
        self.Label2_13.configure(foreground="#000000")
        self.Label2_13.configure(highlightbackground="#d9d9d9")
        self.Label2_13.configure(highlightcolor="black")
        self.Label2_13.configure(text='''Password''')

        self.Button2_14 = Button(self.Dispatcher_reg_frame)
        self.Button2_14.place(relx=0.12, rely=0.81, height=34, width=77)
        self.Button2_14.configure(activebackground="#d9d9d9")
        self.Button2_14.configure(activeforeground="#000000")
        self.Button2_14.configure(background="#b0d852")
        self.Button2_14.configure(borderwidth="0")
        self.Button2_14.configure(disabledforeground="#a3a3a3")
        self.Button2_14.configure(font=font11)
        self.Button2_14.configure(foreground="#000000")
        self.Button2_14.configure(highlightbackground="#d9d9d9")
        self.Button2_14.configure(highlightcolor="black")
        self.Button2_14.configure(pady="0")
        self.Button2_14.configure(text='''Save''')

        self.dispatcher_idno = Entry(self.Dispatcher_reg_frame)
        self.dispatcher_idno.place(relx=0.33, rely=0.2, height=30, relwidth=0.61)

        self.dispatcher_idno.configure(background="white")
        self.dispatcher_idno.configure(disabledforeground="#a3a3a3")
        self.dispatcher_idno.configure(font=font10)
        self.dispatcher_idno.configure(foreground="#000000")
        self.dispatcher_idno.configure(highlightbackground="#d9d9d9")
        self.dispatcher_idno.configure(highlightcolor="black")
        self.dispatcher_idno.configure(insertbackground="black")
        self.dispatcher_idno.configure(selectbackground="#c4c4c4")
        self.dispatcher_idno.configure(selectforeground="black")

        self.dispatcher_name = Entry(self.Dispatcher_reg_frame)
        self.dispatcher_name.place(relx=0.33, rely=0.34, height=30
                , relwidth=0.61)
        self.dispatcher_name.configure(background="white")
        self.dispatcher_name.configure(disabledforeground="#a3a3a3")
        self.dispatcher_name.configure(font=font10)
        self.dispatcher_name.configure(foreground="#000000")
        self.dispatcher_name.configure(highlightbackground="#d9d9d9")
        self.dispatcher_name.configure(highlightcolor="black")
        self.dispatcher_name.configure(insertbackground="black")
        self.dispatcher_name.configure(selectbackground="#c4c4c4")
        self.dispatcher_name.configure(selectforeground="black")

        self.dispatcher_cno = Entry(self.Dispatcher_reg_frame)
        self.dispatcher_cno.place(relx=0.35, rely=0.5,height=30, relwidth=0.61)
        self.dispatcher_cno.configure(background="white")
        self.dispatcher_cno.configure(disabledforeground="#a3a3a3")
        self.dispatcher_cno.configure(font=font10)
        self.dispatcher_cno.configure(foreground="#000000")
        self.dispatcher_cno.configure(highlightbackground="#d9d9d9")
        self.dispatcher_cno.configure(highlightcolor="black")
        self.dispatcher_cno.configure(insertbackground="black")
        self.dispatcher_cno.configure(selectbackground="#c4c4c4")
        self.dispatcher_cno.configure(selectforeground="black")

        self.dispatcher_password = Entry(self.Dispatcher_reg_frame)
        self.dispatcher_password.place(relx=0.35, rely=0.64, height=30
                , relwidth=0.61)
        self.dispatcher_password.configure(background="white")
        self.dispatcher_password.configure(disabledforeground="#a3a3a3")
        self.dispatcher_password.configure(font=font10)
        self.dispatcher_password.configure(foreground="#000000")
        self.dispatcher_password.configure(highlightbackground="#d9d9d9")
        self.dispatcher_password.configure(highlightcolor="black")
        self.dispatcher_password.configure(insertbackground="black")
        self.dispatcher_password.configure(selectbackground="#c4c4c4")
        self.dispatcher_password.configure(selectforeground="black")

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()



