#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 01, 2018 05:49:16 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import StockerRegistration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = StockerRegistration (root)
    StockerRegistration_support.init(root, top)
    root.mainloop()

w = None
def create_StockerRegistration(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = StockerRegistration (w)
    StockerRegistration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_StockerRegistration():
    global w
    w.destroy()
    w = None


class StockerRegistration:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
      #  self.stocker_idno = idno
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Courier New} -size 13 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family {Courier New} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("682x350+334+135")
        top.title("StockerRegistration")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.01, relheight=0.99, relwidth=0.99)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#07f2d3")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=675)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.08, rely=0.04, height=31, width=244)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#b5bbd8")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Stocker Registration''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.01, rely=0.17, height=31, width=54)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#b5bbd8")
        self.Label2.configure(borderwidth="0")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Idno''')

        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.22, rely=0.18, height=21, width=84)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#b5bbd8")
        self.Label3.configure(borderwidth="0")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''....''')
        idno = StockerRegistration_support.autogen_id()
        self.Label3.configure(text=idno)

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.01, rely=0.29, height=31, width=64)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#b5bbd8")
        self.Label4.configure(borderwidth="0")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font9)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Name''')

        self.Label5 = Label(self.Frame1)
        self.Label5.place(relx=0.01, rely=0.4, height=31, width=114)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#b5bbd8")
        self.Label5.configure(borderwidth="0")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font9)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Phone''')

        self.Stocker_username = Entry(self.Frame1)
        self.Stocker_username.place(relx=0.19, rely=0.29, height=30
                , relwidth=0.24)
        self.Stocker_username.configure(background="white")
        self.Stocker_username.configure(disabledforeground="#a3a3a3")
        self.Stocker_username.configure(font="TkFixedFont")
        self.Stocker_username.configure(foreground="#000000")
        self.Stocker_username.configure(highlightbackground="#d9d9d9")
        self.Stocker_username.configure(highlightcolor="black")
        self.Stocker_username.configure(insertbackground="black")
        self.Stocker_username.configure(selectbackground="#c4c4c4")
        self.Stocker_username.configure(selectforeground="black")

        self.Stocker_cno = Entry(self.Frame1)
        self.Stocker_cno.place(relx=0.19, rely=0.4,height=30, relwidth=0.24)
        self.Stocker_cno.configure(background="white")
        self.Stocker_cno.configure(disabledforeground="#a3a3a3")
        self.Stocker_cno.configure(font="TkFixedFont")
        self.Stocker_cno.configure(foreground="#000000")
        self.Stocker_cno.configure(highlightbackground="#d9d9d9")
        self.Stocker_cno.configure(highlightcolor="black")
        self.Stocker_cno.configure(insertbackground="black")
        self.Stocker_cno.configure(selectbackground="#c4c4c4")
        self.Stocker_cno.configure(selectforeground="black")

        self.Stocker_save = Button(self.Frame1)
        self.Stocker_save.place(relx=0.24, rely=0.64, height=34, width=77)
        self.Stocker_save.configure(activebackground="#d9d9d9")
        self.Stocker_save.configure(activeforeground="#000000")
        self.Stocker_save.configure(background="#b5bbd8")
        self.Stocker_save.configure(borderwidth="0")
        self.Stocker_save.configure(command=StockerRegistration_support.save_stocker)
        self.Stocker_save.configure(disabledforeground="#a3a3a3")
        self.Stocker_save.configure(font=font9)
        self.Stocker_save.configure(foreground="#000000")
        self.Stocker_save.configure(highlightbackground="#d9d9d9")
        self.Stocker_save.configure(highlightcolor="black")
        self.Stocker_save.configure(pady="0")
        self.Stocker_save.configure(text='''Save''')

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.5, rely=0.0, relheight=0.93, relwidth=0.0)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#111111")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=-5)

        self.Label6 = Label(self.Frame1)
        self.Label6.place(relx=0.56, rely=0.03, height=31, width=244)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#b5bbd8")
        self.Label6.configure(borderwidth="0")
        self.Label6.configure(compound="center")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font9)
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''View Stock''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.52, rely=0.16, height=31, width=54)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#b5bbd8")
        self.Label2_1.configure(borderwidth="0")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font9)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Idno''')

        self.Stocker_idno = Entry(self.Frame1)
        self.Stocker_idno.place(relx=0.67, rely=0.17,height=30, relwidth=0.23)
        self.Stocker_idno.configure(background="white")
        self.Stocker_idno.configure(disabledforeground="#a3a3a3")
        self.Stocker_idno.configure(font="TkFixedFont")
        self.Stocker_idno.configure(foreground="#000000")
        self.Stocker_idno.configure(highlightbackground="#d9d9d9")
        self.Stocker_idno.configure(highlightcolor="black")
        self.Stocker_idno.configure(insertbackground="black")
        self.Stocker_idno.configure(selectbackground="#c4c4c4")
        self.Stocker_idno.configure(selectforeground="black")

        self.Label4_2 = Label(self.Frame1)
        self.Label4_2.place(relx=0.52, rely=0.41, height=31, width=64)
        self.Label4_2.configure(activebackground="#f9f9f9")
        self.Label4_2.configure(activeforeground="black")
        self.Label4_2.configure(background="#b5bbd8")
        self.Label4_2.configure(borderwidth="0")
        self.Label4_2.configure(disabledforeground="#a3a3a3")
        self.Label4_2.configure(font=font9)
        self.Label4_2.configure(foreground="#000000")
        self.Label4_2.configure(highlightbackground="#d9d9d9")
        self.Label4_2.configure(highlightcolor="black")
        self.Label4_2.configure(text='''Name''')

        self.Label5_3 = Label(self.Frame1)
        self.Label5_3.place(relx=0.51, rely=0.51, height=31, width=114)
        self.Label5_3.configure(activebackground="#f9f9f9")
        self.Label5_3.configure(activeforeground="black")
        self.Label5_3.configure(background="#b5bbd8")
        self.Label5_3.configure(borderwidth="0")
        self.Label5_3.configure(disabledforeground="#a3a3a3")
        self.Label5_3.configure(font=font9)
        self.Label5_3.configure(foreground="#000000")
        self.Label5_3.configure(highlightbackground="#d9d9d9")
        self.Label5_3.configure(highlightcolor="black")
        self.Label5_3.configure(text='''Contact No''')

        self.Stocker_view = Button(self.Frame1)
        self.Stocker_view.place(relx=0.73, rely=0.26, height=34, width=77)
        self.Stocker_view.configure(activebackground="#d9d9d9")
        self.Stocker_view.configure(activeforeground="#000000")
        self.Stocker_view.configure(background="#b5bbd8")
        self.Stocker_view.configure(borderwidth="0")
        self.Stocker_view.configure(command=StockerRegistration_support.view_stocker)
        self.Stocker_view.configure(disabledforeground="#a3a3a3")
        self.Stocker_view.configure(font=font9)
        self.Stocker_view.configure(foreground="#000000")
        self.Stocker_view.configure(highlightbackground="#d9d9d9")
        self.Stocker_view.configure(highlightcolor="black")
        self.Stocker_view.configure(pady="0")
        self.Stocker_view.configure(text='''View''')

        self.Stocker_delete = Button(self.Frame1)
        self.Stocker_delete.place(relx=0.7, rely=0.66, height=34, width=77)
        self.Stocker_delete.configure(activebackground="#d9d9d9")
        self.Stocker_delete.configure(activeforeground="#000000")
        self.Stocker_delete.configure(background="#b5bbd8")
        self.Stocker_delete.configure(borderwidth="0")
        self.Stocker_delete.configure(command=StockerRegistration_support.delete_stocker)
        self.Stocker_delete.configure(disabledforeground="#a3a3a3")
        self.Stocker_delete.configure(font=font9)
        self.Stocker_delete.configure(foreground="#000000")
        self.Stocker_delete.configure(highlightbackground="#d9d9d9")
        self.Stocker_delete.configure(highlightcolor="black")
        self.Stocker_delete.configure(pady="0")
        self.Stocker_delete.configure(text='''Delete''')

        self.Label3_6 = Label(self.Frame1)
        self.Label3_6.place(relx=0.73, rely=0.41, height=21, width=84)
        self.Label3_6.configure(activebackground="#f9f9f9")
        self.Label3_6.configure(activeforeground="black")
        self.Label3_6.configure(background="#b5bbd8")
        self.Label3_6.configure(borderwidth="0")
        self.Label3_6.configure(disabledforeground="#a3a3a3")
        self.Label3_6.configure(foreground="#000000")
        self.Label3_6.configure(highlightbackground="#d9d9d9")
        self.Label3_6.configure(highlightcolor="black")
        self.Label3_6.configure(text='''....''')

        self.Label3_7 = Label(self.Frame1)
        self.Label3_7.place(relx=0.73, rely=0.52, height=21, width=84)
        self.Label3_7.configure(activebackground="#f9f9f9")
        self.Label3_7.configure(activeforeground="black")
        self.Label3_7.configure(background="#b5bbd8")
        self.Label3_7.configure(borderwidth="0")
        self.Label3_7.configure(disabledforeground="#a3a3a3")
        self.Label3_7.configure(foreground="#000000")
        self.Label3_7.configure(highlightbackground="#d9d9d9")
        self.Label3_7.configure(highlightcolor="black")
        self.Label3_7.configure(text='''....''')

        self.Label5_1 = Label(self.Frame1)
        self.Label5_1.place(relx=0.02, rely=0.5, height=31, width=94)
        self.Label5_1.configure(activebackground="#f9f9f9")
        self.Label5_1.configure(activeforeground="black")
        self.Label5_1.configure(background="#b5bbd8")
        self.Label5_1.configure(borderwidth="0")
        self.Label5_1.configure(disabledforeground="#a3a3a3")
        self.Label5_1.configure(font=font9)
        self.Label5_1.configure(foreground="#000000")
        self.Label5_1.configure(highlightbackground="#d9d9d9")
        self.Label5_1.configure(highlightcolor="black")
        self.Label5_1.configure(text='''Password''')
        self.Label5_1.configure(width=94)

        self.Stocker_Pass = Entry(self.Frame1)
        self.Stocker_Pass.place(relx=0.19, rely=0.5,height=30, relwidth=0.24)
        self.Stocker_Pass.configure(background="white")
        self.Stocker_Pass.configure(disabledforeground="#a3a3a3")
        self.Stocker_Pass.configure(font="TkFixedFont")
        self.Stocker_Pass.configure(foreground="#000000")
        self.Stocker_Pass.configure(highlightbackground="#d9d9d9")
        self.Stocker_Pass.configure(highlightcolor="black")
        self.Stocker_Pass.configure(insertbackground="black")
        self.Stocker_Pass.configure(selectbackground="#c4c4c4")
        self.Stocker_Pass.configure(selectforeground="black")






if __name__ == '__main__':
    vp_start_gui()



