#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 21, 2018 07:21:06 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def admin_customer():
    print('AdminHome_support.admin_customer')
    sys.stdout.flush()

def admin_employee():
    print('AdminHome_support.admin_employee')
    sys.stdout.flush()

def admin_logout():
    print('AdminHome_support.admin_logout')
    sys.stdout.flush()

def admin_product():
    print('AdminHome_support.admin_product')
    sys.stdout.flush()

def admin_sales():
    print('AdminHome_support.admin_sales')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def admin_employee():
    pass

def admin_product():
    pass

def admin_customer():
    pass

def admin_sales():
    pass

def admin_logout():
    pass

#if __name__ == '__main__':
 #   import AdminHome
  #  AdminHome.vp_start_gui()


