#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 21, 2018 08:18:40 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def Stocker_registration():
    w.dispatcher_button.pack_forget()
    w.dispatcher_button.place(relx=0.32, rely=0.07, height=34, width=117)

    w.stocker_button.pack()
    w.stocker_button.place(relx=0,rely=0,height=0,width=0)

    w.stocker_reg_frame.pack_forget()
    w.stocker_reg_frame.place(relx=0.02, rely=0.18, relheight=0.77 ,relwidth=0.49)

    w.dispatcher_reg_frame.pack()
    w.dispatcher_reg_frame.place(relx=0,rely=0,height=0,width=0)

def Dispatcher_registration():
    w.stocker_button.pack_forget()
    w.stocker_button.place(relx=0.32, rely=0.07, height=34, width=117)

    w.dispatcher_button.pack()
    w.dispatcher_button.place(relx=0,rely=0,height=0,width=0)

    w.dispatcher_reg_frame.pack_forget()
    w.dispatcher_reg_frame.place(relx=0.5, rely=0.18, relheight=0.77 , relwidth=0.49)

    w.stocker_reg_frame.pack()
    w.stocker_reg_frame.place(relx=0, rely=0, relheight=0 ,relwidth=0)




if __name__ == '__main__':
   import EmployeeHome
   EmployeeHome.vp_start_gui()


