#############################################################################
# Generated by PAGE version 4.13
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 15 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Courier New} -size 13 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Courier New} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 682x350+334+135
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "StockerRegistration"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#07f2d3} -height 345 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 675 
    vTcl:DefineAlias "$top.fra38" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra38
    label $site_3_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text IDNO 
    vTcl:DefineAlias "$site_3_0.lab39" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra40 \
        -borderwidth 2 -relief groove -background {#0c0c0c} -height 345 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width -5 
    vTcl:DefineAlias "$site_3_0.fra40" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text ......... 
    vTcl:DefineAlias "$site_3_0.lab41" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab38 \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -text {Stocker Registration} 
    vTcl:DefineAlias "$site_3_0.lab38" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab40 \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text Name 
    vTcl:DefineAlias "$site_3_0.lab40" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab42 \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text Phone 
    vTcl:DefineAlias "$site_3_0.lab42" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab43 \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text Password 
    vTcl:DefineAlias "$site_3_0.lab43" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#07f2d3} -borderwidth 0 -command save_stocker \
        -disabledforeground {#a3a3a3} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Save 
    vTcl:DefineAlias "$site_3_0.but44" "Save" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent45 \
        -background white -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent47 \
        -background white -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -text { View Stocker} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text IDNO 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent50 \
        -background white -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#07f2d3} -borderwidth 0 -command View_stocker \
        -disabledforeground {#a3a3a3} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Show 
    vTcl:DefineAlias "$site_3_0.but51" "show" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Name 
    vTcl:DefineAlias "$site_3_0.lab52" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Phone 
    vTcl:DefineAlias "$site_3_0.lab53" "Label4_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text ........... 
    vTcl:DefineAlias "$site_3_0.lab54" "Label4_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#07f2d3} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text .......... 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4_6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#07f2d3} -borderwidth 0 -command Delete_stocker \
        -disabledforeground {#a3a3a3} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Delete 
    vTcl:DefineAlias "$site_3_0.but56" "Delete" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab39 \
        -in $site_3_0 -x 7 -y 83 -width 58 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra40 \
        -in $site_3_0 -x 350 -y 0 -width 1 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 124 -y 82 -width 44 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab38 \
        -in $site_3_0 -x 34 -y 10 -width 269 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab40 \
        -in $site_3_0 -x 7 -y 130 -width 62 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab42 \
        -in $site_3_0 -x 6 -y 181 -width 65 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 6 -y 235 -width 95 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 271 -y 281 -width 58 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent45 \
        -in $site_3_0 -x 123 -y 137 -width 204 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 123 -y 189 -width 204 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 124 -y 243 -width 204 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 428 -y 10 -width 180 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 373 -y 85 -width 58 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 459 -y 92 -width 204 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 525 -y 120 -width 65 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 373 -y 172 -width 62 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 371 -y 223 -width 65 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 465 -y 175 -width 65 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 465 -y 223 -width 65 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 582 -y 282 -width 68 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode inside 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 3 -y 3 -width 675 -relwidth 0 -height 345 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

