#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 04, 2018 01:42:56 AM


import sys
from tkinter import messagebox
from firebase import firebase

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def sautogen_id():
    fire = firebase.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/admin/employee/stocker", None)
    result = fire.get("stocker", None)
    idno = ""
    if result == None:
        idno = "100"
    else:
        for x in result:
            pass
        id = int(x)
        id = id + 1
        idno = str(id)

    return idno

def view_stocker():
    idno = w.Entry2.get()
    if idno == "":
        messagebox.showerror("View", "Enter Idno")
    else:
        fire = firebase.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/admin/employee/stocker", None)
        result = fire.get("stocker", idno)
        if result == None:
            messagebox.showerror("View", "Invalid Idno")
            w.Stocker_idno.delete(0, "end")
        else:
            name = result["name"]
            phone = result["phone"]
            w.Label2_3.configure(text=name)
            w.Label2_3.configure(text=phone)


def save_stocker():
    idno = sautogen_id()
    name = w.stocker_name.get()
    phone = w.stocker_phone.get()
    password = w.stocker_password.get()

    if name == "":
        messagebox.showerror("Registration", "Enter Name")
    elif phone == "":
        messagebox.showerror("Registration", "Enter Phone No")
    elif password == "":
        messagebox.showerror("Registration", "Enter Password")
    else:
        fire = firebase.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/admin/employee/stocker", None)
        fire.put("stocker", idno, {"name": name, "phone": phone, "password": password})
        messagebox.showinfo("Registration", "Saved")
        destroy_window()


def delete_stocker():
    idno = w.Entry2.get()
    if idno == "":
        messagebox.showerror("View", "Enter Idno")
    else:
        ans = messagebox.askyesno("Stocker Delete", "ARE YOU SURE")
        if ans:
            fire = firebase.FirebaseApplication("https://merchant-1995r.firebaseio.com/merchant/admin/employee/stocker", None)
            fire.delete("stocker",idno)
            messagebox.showinfo("Delete Confirmation", "Record Deleted")
            destroy_window()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import StockerRegistration
    StockerRegistration.vp_start_gui()


