#############################################################################
# Generated by PAGE version 4.13
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Courier New} -size 15 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI} -size 15 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Segoe UI} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra39
    set site_4_0 $site_3_0.fra46
    set site_4_0 $site_3_0.fra47
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m68" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+429+142
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Employee Home"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra39 \
        -borderwidth 10 -relief groove -background {#21ddea} -height 435 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 585 
    vTcl:DefineAlias "$top.fra39" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra39
    button $site_3_0.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#21ddea} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Stocker 
    vTcl:DefineAlias "$site_3_0.but40" "stocker_button" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#21ddea} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Dispatcher 
    vTcl:DefineAlias "$site_3_0.but41" "dispatcher_button" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra46 \
        -borderwidth 2 -relief groove -background {#d811cb} -height 335 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 285 
    vTcl:DefineAlias "$site_3_0.fra46" "stocker_reg_frame" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra46
    label $site_4_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d811cb} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Stocker Registration} 
    vTcl:DefineAlias "$site_4_0.lab48" "Stocker_registration" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d811cb} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Idno 
    vTcl:DefineAlias "$site_4_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d811cb} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Name 
    vTcl:DefineAlias "$site_4_0.lab50" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d811cb} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Contact 
    vTcl:DefineAlias "$site_4_0.lab51" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d811cb} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Password 
    vTcl:DefineAlias "$site_4_0.lab52" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d811cb} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Save 
    vTcl:DefineAlias "$site_4_0.but53" "Button2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent54 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent54" "stocker_idno" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent55 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent55" "stocker_name" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent56" "stocker_cno" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent57 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -show * 
    vTcl:DefineAlias "$site_4_0.ent57" "stocker_password" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab48 \
        -in $site_4_0 -x 3 -y 9 -width 274 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 14 -y 70 -width 74 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 13 -y 115 -width 74 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 3 -y 164 -width 94 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 4 -y 214 -width 94 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but53 \
        -in $site_4_0 -x 33 -y 271 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent54 \
        -in $site_4_0 -x 100 -y 74 -width 174 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent55 \
        -in $site_4_0 -x 100 -y 120 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 100 -y 168 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent57 \
        -in $site_4_0 -x 100 -y 217 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra47 \
        -borderwidth 2 -relief groove -background {#b0d852} -height 335 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 285 
    vTcl:DefineAlias "$site_3_0.fra47" "Dispatcher_reg_frame" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra47
    label $site_4_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#b0d852} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Dispatcher Registration} 
    vTcl:DefineAlias "$site_4_0.lab58" "Dispatcher_registration" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#b0d852} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Idno 
    vTcl:DefineAlias "$site_4_0.lab59" "Label2_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#b0d852} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Name 
    vTcl:DefineAlias "$site_4_0.lab60" "Label2_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#b0d852} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Contact 
    vTcl:DefineAlias "$site_4_0.lab61" "Label2_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#b0d852} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Password 
    vTcl:DefineAlias "$site_4_0.lab62" "Label2_13" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but63 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#b0d852} -borderwidth 0 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Save 
    vTcl:DefineAlias "$site_4_0.but63" "Button2_14" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent64 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent64" "dispatcher_idno" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent65 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent65" "dispatcher_name" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent66 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent66" "dispatcher_cno" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent67 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent67" "dispatcher_password" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab58 \
        -in $site_4_0 -x 5 -y 5 -width 274 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 16 -y 67 -width 74 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab60 \
        -in $site_4_0 -x 16 -y 112 -width 74 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 11 -y 162 -width 84 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 6 -y 213 -width 94 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but63 \
        -in $site_4_0 -x 36 -y 270 -width 77 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent64 \
        -in $site_4_0 -x 99 -y 68 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent65 \
        -in $site_4_0 -x 99 -y 115 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent66 \
        -in $site_4_0 -x 100 -y 166 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent67 \
        -in $site_4_0 -x 101 -y 215 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but40 \
        -in $site_3_0 -x 40 -y 30 -width 97 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but41 \
        -in $site_3_0 -x 194 -y 32 -width 117 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra46 \
        -in $site_3_0 -x 10 -y 80 -width 285 -relwidth 0 -height 335 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra47 \
        -in $site_3_0 -x 290 -y 80 -width 285 -relwidth 0 -height 335 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m68
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra39 \
        -in $top -x 10 -y 10 -width 585 -relwidth 0 -height 435 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

