#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 21, 2018 07:37:09 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import AdminHome_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Admin_Home (root)
    AdminHome_support.init(root, top)
    root.mainloop()

w = None
def create_Admin_Home(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Admin_Home (w)
    AdminHome_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Admin_Home():
    global w
    w.destroy()
    w = None


class Admin_Home:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 15 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("600x450+411+125")
        top.title("Admin Home")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.02, relheight=0.92, relwidth=0.49)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#be13d8")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=295)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.1, rely=0.07, height=41, width=234)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#be13d8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Admin Home''')

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.24, rely=0.24, height=34, width=147)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#be13d8")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=AdminHome_support.admin_employee)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Employee''')

        self.Button1_1 = Button(self.Frame1)
        self.Button1_1.place(relx=0.24, rely=0.37, height=34, width=147)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#be13d8")
        self.Button1_1.configure(borderwidth="0")
        self.Button1_1.configure(command=AdminHome_support.admin_product)
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font9)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Product''')

        self.Button1_2 = Button(self.Frame1)
        self.Button1_2.place(relx=0.24, rely=0.51, height=34, width=147)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#be13d8")
        self.Button1_2.configure(borderwidth="0")
        self.Button1_2.configure(command=AdminHome_support.admin_customer)
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font=font9)
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Customer''')

        self.Button1_3 = Button(self.Frame1)
        self.Button1_3.place(relx=0.24, rely=0.66, height=34, width=147)
        self.Button1_3.configure(activebackground="#d9d9d9")
        self.Button1_3.configure(activeforeground="#000000")
        self.Button1_3.configure(background="#be13d8")
        self.Button1_3.configure(borderwidth="0")
        self.Button1_3.configure(command=AdminHome_support.admin_sales)
        self.Button1_3.configure(disabledforeground="#a3a3a3")
        self.Button1_3.configure(font=font9)
        self.Button1_3.configure(foreground="#000000")
        self.Button1_3.configure(highlightbackground="#d9d9d9")
        self.Button1_3.configure(highlightcolor="black")
        self.Button1_3.configure(pady="0")
        self.Button1_3.configure(text='''Sales''')

        self.Button1_4 = Button(self.Frame1)
        self.Button1_4.place(relx=0.22, rely=0.81, height=34, width=147)
        self.Button1_4.configure(activebackground="#d9d9d9")
        self.Button1_4.configure(activeforeground="#000000")
        self.Button1_4.configure(background="#be13d8")
        self.Button1_4.configure(borderwidth="0")
        self.Button1_4.configure(command=AdminHome_support.admin_logout)
        self.Button1_4.configure(disabledforeground="#a3a3a3")
        self.Button1_4.configure(font=font9)
        self.Button1_4.configure(foreground="#000000")
        self.Button1_4.configure(highlightbackground="#d9d9d9")
        self.Button1_4.configure(highlightcolor="black")
        self.Button1_4.configure(pady="0")
        self.Button1_4.configure(text='''Logout''')






if __name__ == '__main__':
    vp_start_gui()



