#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 01:10:37 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def delete_dispatcher():
    print('DispatcherRegistration_support.delete_dispatcher')
    sys.stdout.flush()

def save_dispatcher():
    print('DispatcherRegistration_support.save_dispatcher')
    sys.stdout.flush()

def show_dispatcher():
    print('DispatcherRegistration_support.show_dispatcher')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import DispatcherRegistration
    DispatcherRegistration.vp_start_gui()


