#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 04, 2018 01:43:09 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import StockerRegistration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = StockerRegistration_ (root)
    StockerRegistration_support.init(root, top)
    root.mainloop()

w = None
def create_StockerRegistration_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = StockerRegistration_ (w)
    StockerRegistration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_StockerRegistration_():
    global w
    w.destroy()
    w = None


class StockerRegistration_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("700x379+296+173")
        top.title("StockerRegistration ")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.01, relheight=0.99, relwidth=0.99)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#0cf4ae")
        self.Frame1.configure(width=695)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.03, rely=0.05, height=43, width=269)
        self.Label1.configure(background="#0cf4ae")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Stocker Registration''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.03, rely=0.24, height=34, width=58)
        self.Label2.configure(background="#0cf4ae")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Idno''')
        self.Label2.configure(width=58)

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.19, rely=0.27, height=21, width=30)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#0cf4ae")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''..............''')
        idno=StockerRegistration_support.sautogen_id()
        self.Label2_1.configure(text=idno)


        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.01, rely=0.37, height=51, width=90)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#0cf4ae")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font10)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Name''')
        self.Label2_2.configure(width=90)

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.01, rely=0.51, height=61, width=100)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#0cf4ae")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font10)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Phone''')
        self.Label2_3.configure(width=100)

        self.Label2_4 = Label(self.Frame1)
        self.Label2_4.place(relx=0.01, rely=0.69, height=41, width=120)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#0cf4ae")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(font=font10)
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Password''')
        self.Label2_4.configure(width=120)

        self.stocker_name = Entry(self.Frame1)
        self.stocker_name.place(relx=0.19, rely=0.42,height=20, relwidth=0.24)
        self.stocker_name.configure(background="white")
        self.stocker_name.configure(borderwidth="0")
        self.stocker_name.configure(disabledforeground="#a3a3a3")
        self.stocker_name.configure(font="TkFixedFont")
        self.stocker_name.configure(foreground="#000000")
        self.stocker_name.configure(insertbackground="black")

        self.stocker_phone = Entry(self.Frame1)
        self.stocker_phone.place(relx=0.19, rely=0.57,height=20, relwidth=0.24)
        self.stocker_phone.configure(background="white")
        self.stocker_phone.configure(borderwidth="0")
        self.stocker_phone.configure(disabledforeground="#a3a3a3")
        self.stocker_phone.configure(font="TkFixedFont")
        self.stocker_phone.configure(foreground="#000000")
        self.stocker_phone.configure(highlightbackground="#d9d9d9")
        self.stocker_phone.configure(highlightcolor="black")
        self.stocker_phone.configure(insertbackground="black")
        self.stocker_phone.configure(selectbackground="#c4c4c4")
        self.stocker_phone.configure(selectforeground="black")

        self.stocker_password = Entry(self.Frame1)
        self.stocker_password.place(relx=0.19, rely=0.72, height=20
                , relwidth=0.24)
        self.stocker_password.configure(background="white")
        self.stocker_password.configure(borderwidth="0")
        self.stocker_password.configure(disabledforeground="#a3a3a3")
        self.stocker_password.configure(font="TkFixedFont")
        self.stocker_password.configure(foreground="#000000")
        self.stocker_password.configure(highlightbackground="#d9d9d9")
        self.stocker_password.configure(highlightcolor="black")
        self.stocker_password.configure(insertbackground="black")
        self.stocker_password.configure(selectbackground="#c4c4c4")
        self.stocker_password.configure(selectforeground="black")
        self.stocker_password.configure(show="*")

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.5, rely=0.03, relheight=0.95, relwidth=0.0)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#141414")
        self.Frame2.configure(width=-5)

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.31, rely=0.83, height=43, width=78)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0cf4ae")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(command=StockerRegistration_support.save_stocker)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')
        self.Button1.configure(width=78)

        self.Label1_8 = Label(self.Frame1)
        self.Label1_8.place(relx=0.55, rely=0.05, height=43, width=269)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#0cf4ae")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(font=font9)
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''View Stocker''')

        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.53, rely=0.22, height=51, width=74)
        self.Label3.configure(background="#0cf4ae")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Idno''')
        self.Label3.configure(width=74)

        self.Entry2 = Entry(self.Frame1)
        self.Entry2.place(relx=0.69, rely=0.26,height=20, relwidth=0.24)
        self.Entry2.configure(background="white")
        self.Entry2.configure(borderwidth="0")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Button2 = Button(self.Frame1)
        self.Button2.place(relx=0.76, rely=0.33, height=43, width=60)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#0cf4ae")
        self.Button2.configure(borderwidth="0")
        self.Button2.configure(command=StockerRegistration_support.view_stocker)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font10)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''View''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.51, rely=0.47, height=51, width=90)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#0cf4ae")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font10)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Name''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.73, rely=0.47, height=51, width=90)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#0cf4ae")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font10)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''...........................''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.52, rely=0.62, height=51, width=90)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#0cf4ae")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font10)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Phone''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.75, rely=0.65, height=53, width=93)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#0cf4ae")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font10)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''........................''')

        self.Button3 = Button(self.Frame1)
        self.Button3.place(relx=0.78, rely=0.82, height=43, width=76)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#0cf4ae")
        self.Button3.configure(borderwidth="0")
        self.Button3.configure(command=StockerRegistration_support.delete_stocker)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font10)
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Delete''')






if __name__ == '__main__':
    vp_start_gui()



