#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 28, 2018 04:43:03 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unknown_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Home_ (root)
    unknown_support.init(root, top)
    root.mainloop()

w = None
def create_Home_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Home_ (w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Home_():
    global w
    w.destroy()
    w = None


class Home_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("248x362+376+145")
        top.title("Home ")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.04, rely=0.03, relheight=0.95, relwidth=0.87)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#19bdf9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=215)

        self.admin_login = Button(self.Frame1)
        self.admin_login.place(relx=0.23, rely=0.14, height=34, width=107)
        self.admin_login.configure(activebackground="#d9d9d9")
        self.admin_login.configure(activeforeground="#000000")
        self.admin_login.configure(background="#19bdf9")
        self.admin_login.configure(borderwidth="0")
        self.admin_login.configure(command=unknown_support.Admin_login)
        self.admin_login.configure(disabledforeground="#a3a3a3")
        self.admin_login.configure(font=font9)
        self.admin_login.configure(foreground="#000000")
        self.admin_login.configure(highlightbackground="#d9d9d9")
        self.admin_login.configure(highlightcolor="black")
        self.admin_login.configure(pady="0")
        self.admin_login.configure(text='''Admin''')

        self.stocker_login = Button(self.Frame1)
        self.stocker_login.place(relx=0.23, rely=0.39, height=34, width=107)
        self.stocker_login.configure(activebackground="#d9d9d9")
        self.stocker_login.configure(activeforeground="#000000")
        self.stocker_login.configure(background="#19bdf9")
        self.stocker_login.configure(borderwidth="0")
        self.stocker_login.configure(command=unknown_support.Stocker_login)
        self.stocker_login.configure(disabledforeground="#a3a3a3")
        self.stocker_login.configure(font=font9)
        self.stocker_login.configure(foreground="#000000")
        self.stocker_login.configure(highlightbackground="#d9d9d9")
        self.stocker_login.configure(highlightcolor="black")
        self.stocker_login.configure(pady="0")
        self.stocker_login.configure(text='''Stocker''')

        self.dispatcher_login = Button(self.Frame1)
        self.dispatcher_login.place(relx=0.19, rely=0.61, height=54, width=137)
        self.dispatcher_login.configure(activebackground="#d9d9d9")
        self.dispatcher_login.configure(activeforeground="#000000")
        self.dispatcher_login.configure(background="#19bdf9")
        self.dispatcher_login.configure(borderwidth="0")
        self.dispatcher_login.configure(command=unknown_support.Dispatcher_login)
        self.dispatcher_login.configure(disabledforeground="#a3a3a3")
        self.dispatcher_login.configure(font=font9)
        self.dispatcher_login.configure(foreground="#000000")
        self.dispatcher_login.configure(highlightbackground="#d9d9d9")
        self.dispatcher_login.configure(highlightcolor="black")
        self.dispatcher_login.configure(pady="0")
        self.dispatcher_login.configure(text='''Dispatcher''')






if __name__ == '__main__':
    vp_start_gui()



