#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 19, 2018 05:48:17 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

# if __name__ == '__main__':
#     import AdminHome
#     AdminHome.vp_start_gui()

def admin_stocker():
    import StockerRegistration
    StockerRegistration.vp_start_gui()

def admin_dispatcher():
    import DispatcherRegistration
    DispatcherRegistration.vp_start_gui()

def admin_employee():
    pass

def admin_product():
    pass

def admin_customer():
    pass

def admin_sales():
    pass
from tkinter import messagebox
def admin_logout():
    ans = messagebox.askyesno("Admin Logout","Logout Conformation")
    if ans:
        destroy_window()

